### ISSUE TITLE
The suggested way of "iwr ... | iex" doesn't start the script (hangs?)

### ISSUE THREAD

**Issue by VioletGiraffe** [ChrisTitusTech/winutil#1018]
I have a computer where I wanted to use the tweaker but discovered that it doesn't run. After pasting `iwr -useb https://christitus.com/win | iex` and pressing Enter the cursor moves to the next line, and nothing more happens (I've waited for 10 minutes). How can I troubleshoot this?

![image](https://github.com/ChrisTitusTech/winutil/assets/1175926/03ae0b5a-f225-46f0-a868-edca5d3f7a6b)

**Comment by ChrisTitusTech** [comment]
What version of windows are you running?

**Comment by VioletGiraffe** [comment]
22H2 (19045.2273)

**Comment by ChrisTitusTech** [comment]
I am unable to reproduce this issue. I'd recommend setting your DNS to 1.1.1.1 or another dns that will resolve the address properly.

**Comment by jtmaston** [comment]
Hi! I had the same issue, with my dns set to cloudflare (1.1.1.1) and alternate set to google (8.8.8.8). I am using Win10 pro 22H2 (the tiny10 variant). Not sure if the issue could be from tiny10, but I've had it running in the past without any trouble. For me, the problem was I was using Cloudflare Warp. After disabling it, the script ran without issue.
