### ISSUE TITLE
PowerShell comand Get-ComputerRestorePoint not available on PS 7.3.7

### ISSUE THREAD

**Issue by mmarigo** [ChrisTitusTech/winutil#1078]
Some comands ran by the tool (i.e.: **Get-ComputerRestorePoint**) are not available in recent PowerShell versions.
**Get-ComputerRestorePoint** is available in PS 5.1 but **is not available in PS 7.2 or 7.3**.

![PS 7 3 7](https://github.com/ChrisTitusTech/winutil/assets/5967135/768c8ee7-14fb-4262-8c63-073cb9b5081e)

**Comment by ChrisTitusTech** [comment]
Hmmm I'm testing on 7.3. It's there... Are you using a custom ISO where the system restore is stripped out? 
![image](https://github.com/ChrisTitusTech/winutil/assets/7896101/15aac0f9-17be-4a51-a6e8-5998dc4cfba3)

**Comment by mmarigo** [comment]
I searched **Get-ComputerRestorePoint** in PowerShell docs and I found it in **PowerSell 5.1**  (as part of **Microsoft.PowerShell.Management**)
I don't find **Get-ComputerRestorePoint** in **PowerShell 7.2 (LTS)** or **PowerShell 7.3**.

[Microsoft PowerShell 7.3 docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/?view=powershell-7.3)

My Computer is running a standard (downloaded from Microsoft) **Windows 10 Pro** - Italian language.

**Comment by mmarigo** [comment]
I found the reason:
[Differences between Windows PowerShell 5.1 and PowerShell 7.x](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7.3)

Take a look at **Cmdlets removed from PowerShell**

**Comment by ChrisTitusTech** [comment]
Yeah if you launch powershell 7 (AKA Powershell Core) from the start menu apps menu, you will run into all kind of problems due to the legacy powershell commands not supported. 

However, launching Windows Terminal (Admin) and Powershell 7 it doesn't have issues with those commands. 

There are other methods of creating restore points using WMI classes that would be universal with core, but then you run into a backwards compatibility issue. 

However, I can introduce a layer that would detect older compatibility with cmdlets removed in ps core, or use the newer wmi classes. It's pretty low on my priority list since everyone can just launch Windows Terminal with Admin, but its good to plan for the future.

**Comment by mmarigo** [comment]
I have the same behavior if i run PS from Windows Terminal (see the image of my first post) or standalone.
Just now I tried with another PC with PS 7.3 and the comand works fine.
Microsoft ... wtf!
Thank you Chris for your work!
Bye
