### ISSUE TITLE
Chris titus - Still love this winutil ! BigUp

### ISSUE THREAD

**Issue by anonyao** [ChrisTitusTech/winutil#1081]
Hello @ChrisTitusTech , Broo as always i love it , good updates / progs/ tweaks , have worked without one error last months maby some but its becuse i kill this pc with other things ;D  but brooo u have a problem i saw many times since last winUpdate - MSstore Apps dont get uninstalled , its ofen like this but 2-3 times and restart pc and it done, but now Nothing removes/Uninstalls only egde kinda
AND I HATE WINDOWS SERVICES + APPS who rape me in background haha, { Remove-MSStoreApps , Dont works :/ } 
And can i come with a tip , i know u have Ultimate Performance power scheme / But i always use (fr33shy @youtube optimze) And " Bitsum Highest Performance Power Scheme srsly Works better } if u have time and want can u add it to "apps" or  INTELLIGENT Standby list Cleaner , and i can Reconfig it my self with bitsum Peace

**Comment by ChrisTitusTech** [comment]
Many of these MS Store apps are dependencies of other programs microsoft products rely on. I removed the MS Store App option because of this. I'm working to add a general debloat that removes things that aren't dependencies from other products. 
As far as Ultimate Performance Power Scheme that is already there in the tweaks. Just add it and switch the scheme over. There is process lasso in the programs that can also do the Bitsum tweak you mention.
