### ISSUE TITLE
The Connection to the Remote Server could not be established

### ISSUE THREAD

**Issue by GermanYoshi** [ChrisTitusTech/winutil#1135]
![image](https://github.com/ChrisTitusTech/winutil/assets/39739909/36674f36-6af8-4f7b-a873-68210a715113)

it is not the dns, for info i live in germany

![image](https://github.com/ChrisTitusTech/winutil/assets/39739909/1e74609e-de81-4f3c-a04b-1c914f0c21ad)

**Comment by KonTy** [comment]
can you post results of a ping and tracert

PS C:\Users\asdf> tracert christitus.com

Tracing route to christitus.com [104.26.3.223]
over a maximum of 30 hops:

**Comment by NileshwarBhaumik** [comment]
I have the same issue ..
![image](https://github.com/ChrisTitusTech/winutil/assets/57986011/b5b27a05-0951-4dbc-8f21-19e053762f0b)

**Comment by GermanYoshi** [comment]
> tracert christitus.com

![image](https://github.com/ChrisTitusTech/winutil/assets/39739909/1926ed1a-78bb-4da2-b5ed-0042765b8f7b)

**Comment by KonTy** [comment]
sorry for the back and forth, I should have asked for it earlier when you type https://christitus.com/win does PowerShell script load and you can see it without issues? Or you get an error?

Also I do see requests timing out in the middle. Maybe Ipv6 issue.??? Have you tried forcing ipv4 and seeing if that fixes the issue?

**Comment by NileshwarBhaumik** [comment]
Tried to run the script this time with ipv4 but now new errors are there 
![image](https://github.com/ChrisTitusTech/winutil/assets/57986011/37c1755d-2be8-480d-8c39-89f7afa7da47)
after forcing it to ipv4 
![image](https://github.com/ChrisTitusTech/winutil/assets/57986011/8968ca96-28f3-4f4d-9c8f-71d43e7a731d)
plus typing https://christitus.com/win does not load powershell script for me

**Comment by GermanYoshi** [comment]
> sorry for the back and forth, I should have asked for it earlier when you type https://christitus.com/win does PowerShell script load and you can see it without issues? Or you get an error?
> 
> Also I do see requests timing out in the middle. Maybe Ipv6 issue.??? Have you tried forcing ipv4 and seeing if that fixes the issue?

![image](https://github.com/ChrisTitusTech/winutil/assets/39739909/ac982a32-a8f3-4f3c-804c-2501539edfc6)
Browser works fine.
Also tried Ipv4 same issue there
Also Set Ipv6 DNS to Cloudflare

**Comment by KonTy** [comment]
it could be censorship in Germany, like in India they are blocking access to raw files. You can download the tool manually and run it from local hard drive. Also try steps that are outlined on the front page of winutil that shows you how to get around censorship in India, try it it might work for you too.

**Comment by NileshwarBhaumik** [comment]
Thank you so much @KonTy  really appreciate the help ... but could you just guide me where should i download the files from .. i mean i am new in using GitHub

**Comment by KonTy** [comment]
@NileshwarBhaumik  oh sure 

-- SAVING IT --
just open winutil.ps1 in the code section https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1 
click Ctrl-A to select the whole file. Press Ctrl-C (or Ctrl-Insert) to copy the file into the clip board. Open file explorer, navigate to a directory where you want winutil.ps1, right click and choose New/Text Documnt. Windows will Open a Notepad. Paste the text into this new file Ctrl-V (or Shift-Insert). Then File/Save As Winutil.ps1.

-- RUNNING IT --
After you save it, open a new PowerShell window in Admin mode by pressing Windows key->Type PowerShell->Press Ctrl-Shift-Enter to launch as Admin. Then Cd into the directory where you saved your winutil.ps1 file and type .\winutil.ps1.  Done.


Or you can come here https://github.com/ChrisTitusTech/winutil/blob/main/winutil.ps1 
Click download button in the right corner. Save it to your downloads folder
<img width="982" alt="image" src="https://github.com/ChrisTitusTech/winutil/assets/9524513/f6883d5c-9da7-4d27-a529-2ed1b42a350b">
And then continue from --RUNNING IT-- Step above

PS. Make sure you run powershell as admin, there is a bug in winutil if you run it as a normal user it will try to elevate itself to admin and redownload file github, which we established from this thread will fail for you. This was fixed in this PR, but it is not in the main branch yet https://github.com/ChrisTitusTech/winutil/pull/1129/commits/eb7f3b1d427bf2a803949bae47d95fe584319662
