### ISSUE TITLE
App doesn't get downloaded with included instructions

### ISSUE THREAD

**Issue by Build-0-Matic** [ChrisTitusTech/winutil#1150]
Using the included download and install instructions causes an avalanche of errors.

To reproduce:
open Powershell on Windows 10 as administrator.
type 
`irm https://christitus.com/win | iex`
or
`iwr -useb https://christitus.com/win | iex`

And it will give the following error sequence
```
iex : At line:6143 char:5
+     class WingetFailedInstall : Exception {
+     ~~~~~
Class keyword is not allowed in ConstrainedLanguage mode.
At line:6143 char:11
+     class WingetFailedInstall : Exception {
+           ~~~~~~~~~~~~~~~~~~~
Unexpected token 'WingetFailedInstall' in expression or statement.
At line:6149 char:5
+     class ChocoFailedInstall : Exception {
+     ~~~~~
Class keyword is not allowed in ConstrainedLanguage mode.
At line:6149 char:11
+     class ChocoFailedInstall : Exception {
+           ~~~~~~~~~~~~~~~~~~
Unexpected token 'ChocoFailedInstall' in expression or statement.
At line:6155 char:5
+     class GenericException : Exception {
+     ~~~~~
Class keyword is not allowed in ConstrainedLanguage mode.
At line:6155 char:11
+     class GenericException : Exception {
+           ~~~~~~~~~~~~~~~~
Unexpected token 'GenericException' in expression or statement.
At line:1 char:34
+ irm https://christitus.com/win | iex
+                                  ~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : ClassesNotAllowedInConstrainedLanguage,Microsoft.PowerShell.Commands.InvokeExpressionCom
   mand
```

**Comment by oonixgui** [comment]
I started seeing the same errors tonight.  I had to fight my way thru the recent MS update patch BS and thought it was yet another thing broken.

**Comment by Build-0-Matic** [comment]
At least it's good to see it isn't just me...
I tried cloning the Github on a fresh install of Windows 11 and using it from there and it still wouldn't work... all it did is give me different errors.

**Comment by FanieVenter** [comment]
looks like error from language

**Comment by Build-0-Matic** [comment]
I don't know but I doubt it as the computers are running in US English. Granted the keyboard layout is Canadian French, but that shouldn't affect the script as it's only used for entering information, not running.

**Comment by Build-0-Matic** [comment]
I tried it on yet another computer last night and I think I found out what the underlying problem is!
A lot of security apps will lock-out the powershell or cripple it in a way that prevents this from running.
But on a fresh install, it runs fine...
Unless the real problem is discovered (or a workaround found), I would strongly suggest that a warning be added to the readme saying that this is recommended for fresh installs and might not work on an old install.

**Comment by oonixgui** [comment]
I'm seeing this thread/chain of comments about 24hr after the most recent post and I'm still getting the same error.  I am running the command on "standard" English on a Win10 PC.  I haven't changed or modified my Powershell and am using what Windows installed by default which is still PS 5.x.  I use the web-based version of Chris' tool - nothing is installed locally (yet).

I'm chasing down the fonts clue as I did have a problem with the MS October patches failing (KB5031356).  One of the "clues" to chase down was that my reserve system partition had run out of space.    As a suggestion to try to free up space, MS mentioned removing the fonts found in  \EFI\Microsoft\Boot\Fonts on this hidden volume of my C:\ drive.   "The System Reserved Partition (SRP) may be full."  Error code at fail from MS before it tried rolling things back:   0x800f0922.

No bueno = false clue or at least it didn't work or apply.  The October update patch was not installing as I used the Chris' cool tool to delete Edge.  Were these fonts being used in a lame way as a result of this cumulative update??   So, I installed the latest version of Edge and the patch installed after a bajillion previous attempts to figure it out.  Root cause of the patch issue = missing Edge.

So, the $$1M question - does the WinTool script or Powershell require something in  this fonts dir that has been cleared?  WHY???  I'm trying to find a way to get these fonts back so I can test it out.

![fonts removed from hidden system partition](https://github.com/ChrisTitusTech/winutil/assets/92661093/251ba2b5-982f-4926-a46c-76ec2ddef1b6)

Maybe this helps, ... or not.  Another rabbit hole?

**Comment by Build-0-Matic** [comment]
I did a bit or research and it seems that what Microsoft calls "Language" in Powershell has nothing to do with the "Language" we see on the UI.

> PowerShell Constrained Language is a [language mode](https://devblogs.microsoft.com/powershell/a-comparison-of-shell-and-scripting-language-security/) of PowerShell designed to support day-to-day administrative tasks, yet restrict access to sensitive language elements that can be used to invoke arbitrary Windows APIs.
[https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/](url)

> I'm chasing down the fonts clue as I did have a problem with the MS October patches failing (KB5031356). One of the "clues" to chase down was that my reserve system partition had run out of space. As a suggestion to try to free up space, MS 
As for the reserved partition running out of space, I never heard about this one.
You might get a better chance to fix this by resizing the partition with Parted Magic... but that's just a wild guess. But one thing's for sure, if you go that route, be prepared for a looooooooong process.
Have you thought of simply running the Disk Clean-Up app in admin mode and removing the old leftover update uninstall files? I do a few times a year and I'm always surprised at the amount of junk that is cluttering the drive.

**Comment by oonixgui** [comment]
I debated about even mentioning the partition and fonts.  Both were irrelevant, but it was part of the process of figuring out the KB patch issue.  Always amazing how many paths are suggested that don't apply.  The drive is GPT and the partitioning is staying put from legacy MBR.  It has zero impact on the issue and was entirely the fault of MS demanding Edge to be part of the patch install. Shameful.

Moving on, yes, I discoverd the language mode has nothing to do with human language or fonts.  It is about the constrained mode - a permissions thing.  This is in constrast to "FullLanguage" mode which is apparently the opposite of the current setting.  It ties your script's hands, so to speak, from doing rogue things.  Ok.  I'm surprised Chris hasn't surfaced on this issue as it is his code.  I guess we are on are own to keep digging.  The links and info I have found on this mode thing have been useless in  how to fix, adjust, or abandon.  I can assume something in the current load of PowerShell is now wankered and that opens ..... more rabbit holes.  It is being set or forced for my PS session now.  I knew nothing about this prior to the utility failing miserably, but consistently.  This doesn't look like Kansas anymore ...

**Comment by Build-0-Matic** [comment]
I will have to take a loot at this.
I've got a computer on my desk that is waiting for a fresh Win10 install. As soon as I get to finish work on it, I'll see if it's something that is related to an old install vs. fresh one.
I'm slipstreaming the latest updates in this installer, so we'll also see if it's a recent update thing or something else.
I know that it works flawless on a fresh Win11 install... so it might also be that the Win10 support has been accidentally dropped.

**Comment by oonixgui** [comment]
IMPORTANT SUGGESTION:  The video I mentioned above is highly worth watching as it makes this very clear.  
You can verify you System Variable " __PSLockDownPolicy " <<< 2 underscores at front of the variable name
![image](https://github.com/ChrisTitusTech/winutil/assets/92661093/79df9d4f-72a0-47df-8e87-1e421eab1a61)


Be sure to verify the setting for the language mode BEFORE you make any more changes.  I'm pretty sure you have a setting of Constrained instead of FULL.  You may not need to go thru all the hassle of a reload (your option/threshold of pain) if you simply change the setting.  However, if  you are certain you must reload, again check the value of the setting so you have something to compare.  The reload will not have anything to do with the setting as it could default either way.

It's really easy to do in the PowerShell window: (examples follow - just copy and paste into your shell):
PS C:\> $ExecutionContext.SessionState.LanguageMode
FullLanguage   <<< if in FULL, the util works

![image](https://github.com/ChrisTitusTech/winutil/assets/92661093/1c046264-7a0c-4d29-bf06-4a6180b954fb)

IF Constrained is set, you will instead see:
PS C:\> $ExecutionContext.SessionState.LanguageMode
ConstrainedLanguage  <<< if in CONSTRAINED - the util will not be permitted to run

Good luck with your mission.

**Comment by Build-0-Matic** [comment]
That's exactly what I have right now: __PSLockDownPolicy=4
Constrained language.

I'll have to make a batch script that changes that before running Debloater and then returns it to it's current state for security.
