### ISSUE TITLE
Updated UI/UX

### ISSUE THREAD

**Issue by giannisgx89** [ChrisTitusTech/winutil#1225]
**Is your feature request related to a problem? Please describe.**
No, it's a suggestion for updated UI/UX

**Describe the solution you'd like**
I attached the updated UI/UX
![WinUtil Updated UI-UX](https://github.com/ChrisTitusTech/winutil/assets/5347711/82e4f25f-95d2-48e2-a161-5bb438993111)

**Additional context**
Since you are using the new logo I though of redesigning the current WinUtil user interface cause colors are all over the place right now.
I did that because my earlier concept of WinUI 3 for WinUtil will take a long time to complete I guess, so this one should be more viable and easier to do. 😅

Here is also the Figma file if anyone wants to use check out the new icons, spaces, colors, font sizes etc.
https://drive.google.com/file/d/1VkN83fu5kO47GDRQSp020i34Vv7iMFO9/view?usp=sharing

**Comment by giannisgx89** [comment]
I have no idea how Powershell scripts work, just wanted to design something because I don't like the current look. 😅

**Comment by Khalylexe** [comment]
fair ur design is much cleaner and more appealing if its possible we would love this

**Comment by giannisgx89** [comment]
> Not possible with basic xaml to my knowledge.
> 
> I can do this in a WinUI3 library using C#, but that isn't a script but a binary at that point.

Hello Chris, I found this YouTube video which has almost every element I showed in my concept. Icons, buttons, colors, rounded corners, divider, scrollbars, animation(not needed) etc. The only thing it lacks is the black title bar.

https://www.youtube.com/watch?v=A7GdL8Uj1IM

**Comment by CatsArmy** [comment]
not sure if this is still relevant but you might be able to use [WinUIShell](https://github.com/mdgrs-mei/WinUIShell)
[PS Gallary](https://www.powershellgallery.com/packages/WinUIShell/0.2.0) 

the dev of this package also [linked this Demo by PowerShell community](https://www.youtube.com/watch?v=-aDWww5SWOs) in a discord server as a showcase.

again not sure if this is relevant nowadays but i thought id share this new PowerShell module. not sure if it has what this project needs nor if the project is even looking for Updating the UI/UX in a major way but this could help if that day ever comes.

P.S i know this issue is closed i just don't think this deserves a new issue.
