### ISSUE TITLE
MicroWin: Cannot use Windows 11 Pro SKU

### ISSUE THREAD

**Issue by dreamsyntax** [ChrisTitusTech/winutil#1236]
**Describe the bug**
Choosing Windows 11 Pro in MicroWin always results in this error.

**To Reproduce**
1. Launch Powershell via Windows Terminal as Admin on Windows 11 23H2
2. Use irm command to launch winutil 23.11.28
3. Click MicroWin
4. Select Windows 11 23H2 iso, which is placed in C:\
5. After the initial processing, pick Windows 11 Pro SKU
6. The following error occurs

![win11pro-microwin-23.11.28.txt](https://github.com/ChrisTitusTech/winutil/files/13537298/win11pro-microwin-23.11.28.txt)
```
====Chris Titus Tech=====                                                                                               =====Windows Toolbox=====
Checking if Chocolatey is Installed...
Chocolatey Already Installed
File already exists at: C:\Users\user\AppData\Local\Temp\cttlogo.png
Invoking WPFGetIso
         _                     __    __  _
  /\/\  (_)  ___  _ __   ___  / / /\ \ \(_) _ __
 /    \ | | / __|| '__| / _ \ \ \/  \/ /| || '_ \
/ /\/\ \| || (__ | |   | (_) | \  /\  / | || | | |
\/    \/|_| \___||_|    \___/   \/  \/  |_||_| |_|
oscdimge.exe on system: True
File path C:\Win11_23H2_English_x64.iso
Mounting Iso. Please wait.
Done mounting Iso MSFT_DiskImage (ImagePath = "C:\Win11_23H2_English_x64.iso", StorageType = 1)
Iso mounted to 'D'
Setting up mount dir and scratch dirs
Done setting up mount dir and scratch dirs
Copying Windows image. This will take awhile, please don't use UI or cancel this step!
Copy 1031(s) from D: to c:\microwin
Copy complete! Total Time: 0m20s
Getting image information c:\microwin\sources\install.wim
Selected value '1 : Windows 11 Home'.....
Done reading and unpacking ISO

*********************************
Check the UI for further steps!!!
Index chosen: '6' from 6 : Windows 11 Pro
Mounting Windows image. This may take a while.
Mounting complete! Performing removal of applications...
Remove Features from the image
Removing features complete!
Removing Appx Bloat
Invoke-WPFMicrowin : An unexpected error occurred: The specified image is invalid.
Unmount the image or clean up the Wim and then try again.
At line:1940 char:24
+         "WPFMicrowin" {Invoke-WPFMicrowin}
+                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-WPFMicrowin

Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Cleaning up image...
Cleanup complete.
Unmounting image...
Exporting image into c:\microwin\sources\install2.wim
Remove old 'c:\microwin\sources\install.wim' and rename c:\microwin\sources\install2.wim
Windows image completed. Continuing with boot.wim.
Mounting boot image c:\microwin\sources\boot.wim into c:\microwinscratch
Loading registry...
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
Bypassing system requirements on the setup image
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Unmounting image...
Creating ISO image

OSCDIMG 2.56 CD-ROM and DVD-ROM Premastering Utility
Copyright (C) Microsoft, 1993-2012. All rights reserved.
Licensed only for producing Microsoft authorized content.


Scanning source tree (500 files in 43 directories)
Scanning source tree complete (946 files in 86 directories)

Computing directory information complete

Image file is 6210781184 bytes (before optimization)

Writing 946 files in 86 directories to C:\Users\user\AppData\Local\Temp\microwin.iso

100% complete

Storage optimization saved 4 files, 24576 bytes (0% of image)

After optimization, image file is 6212876288 bytes
Space saved because of embedding, sparseness or optimization = 24576

Done.
 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)
ISO creation failed. The  c:\microwin  directory has not been removed.
```

Note I've also deleted the `C:\microwin` and `C:\microwinscratch` folders completely each attempt, though I had to use linux to delete these folders for some reason, despite being admin.

Additionally, in the logs it mentions Windows 11 Home for some reason during ISO read.

**Expected behavior**
MicroWin should be able to succeed with Windows 11 Pro SKU

**Comment by KALIXHOSTING** [comment]
Try it again I was able to create ISO Successfully Just Make sure u backup your drivers cause sometimes u will experience that issue with no hard drive

**Comment by dreamsyntax** [comment]
> @dreamsyntax Grab Your ISO from Rufus 4.3 https://github.com/pbatard/rufus/releases/download/v4.3/rufus-4.3.exe
> 
> And Restest 
> 
> 
> As you can see here it works perfectly with no issues  Ran in terminal as admin on Windows 11 23h2
> 
> see screenshots
> 
> 
> 

Can you post the SHA1 of your ISO? The filesize seems the same.

Can you also try the feature flags all disabled? (edge, defender, etc)

**Comment by KALIXHOSTING** [comment]
> SHA1

 Get-FileHash "C:\Win11_23H2_English_x64.iso" -Algorithm SHA1 | Format-List


Algorithm : SHA1
Hash      : 9D18F7814564421381C94E13C09A9C427BAF8018
Path      : C:\Win11_23H2_English_x64.iso


*********************************
Check the UI for further steps!!!
Index chosen: '6' from 6 : Windows 11 Pro
Mounting Windows image. This may take a while.
Mounting complete! Performing removal of applications...
Remove Features from the image
Removing features complete!
Removing Appx Bloat
Removing Defender
Removing Edge
Removal complete!
Create unattend.xml
Done Create unattend.xml
Copy unattend.xml file into the ISO
Done Copy unattend.xml
Create FirstRun
Done create FirstRun
Copy FirstRun.ps1 into the ISO
Done copy FirstRun.ps1
Copy link to winutil.ps1 into the ISO
ICO file created at: C:\Users\DHL\AppData\Local\Temp\cttlogo.ico
Shortcut to winutil created at: c:\microwinscratch\Windows\Users\Default\Desktop\WinUtil.lnk
Copy checkinstall.cmd into the ISO
Done copy checkinstall.cmd
Creating a directory that allows to bypass Wifi setup
Loading registry
Disabling Teams
Done disabling Teams
Bypassing system requirements (system image)
Removing Edge icon from taskbar
Edge icon removed from taskbar
Setting all services to start manually
Enabling Local Accounts on OOBE
Disabling Sponsored Apps
Done removing Sponsored Apps
Disabling Reserved Storage
Changing theme to dark. This only works on Activated Windows
Unmounting Registry...
Cleaning up image...
Cleanup complete.
Unmounting image...
Exporting image into c:\microwin\sources\install2.wim
Remove old 'c:\microwin\sources\install.wim' and rename c:\microwin\sources\install2.wim
Windows image completed. Continuing with boot.wim.
Mounting boot image c:\microwin\sources\boot.wim into c:\microwinscratch
Loading registry...
Bypassing system requirements on the setup image
Unmounting Registry...
Unmounting image...
Creating ISO image

OSCDIMG 2.56 CD-ROM and DVD-ROM Premastering Utility
Copyright (C) Microsoft, 1993-2012. All rights reserved.
Licensed only for producing Microsoft authorized content.


Scanning source tree (500 files in 43 directories)
Scanning source tree complete (946 files in 86 directories)

Computing directory information complete

Image file is 5698584576 bytes (before optimization)

Writing 946 files in 86 directories to C:\Users\DHL\AppData\Local\Temp\microwin.iso

100% complete

Storage optimization saved 4 files, 24576 bytes (0% of image)

After optimization, image file is 5700669440 bytes
Space saved because of embedding, sparseness or optimization = 24576

Done.
 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)
Done. ISO image is located here: C:\Users\DHL\AppData\Local\Temp\microwin.iso
Performing Cleanup
![Screenshot 2023-12-04 at 1 28 58 PM](https://github.com/ChrisTitusTech/winutil/assets/93708739/0c3a2a90-aeb6-4098-8acc-0094921d951a)

And Again A Successful MicroWin.iso


So The Issue Is on your PC or ISO u are using

**Comment by KALIXHOSTING** [comment]
@dreamsyntax I would suggest try it on a vm on ur latpop 

Because that is strange as it should work with no issues even with those settings applied I tested it out and still successful

**Comment by KALIXHOSTING** [comment]
@dreamsyntax Glad it worked for you and yes no update is needed but it’s good to have 

and Thank U I’ll keep that in Mind

**Comment by simonboet** [comment]
I've just had the same issue.
