### ISSUE TITLE
why forcing chocolatey install? 

### ISSUE THREAD

**Issue by kiena0573** [ChrisTitusTech/winutil#1248]
how to run this script without installing chocolatey? thanks in advance.

**Comment by 0hip** [comment]
> how to run this script without installing chocolatey? thanks in advance.

What I did was: create a file named chocolatey (with no extension) in C:\ProgramData
![image](https://github.com/ChrisTitusTech/winutil/assets/90657954/12549084-1dbf-45e6-b3a9-3a58d0341eaa)
then run the script. There will be some errors due to not finding chocolatey or such but the script will run. Obviously those actions depending on choco will not run as expected.

**Comment by kiena0573** [comment]
thanks mate

**Comment by dreamsyntax** [comment]
You can run this instead to use winutil without installing chocolatey:
`(irm https://christitus.com/win) -replace 'function Install-WinUtilChoco {','function Install-WinUtilChoco {return' | iex`
credit: https://github.com/ChrisTitusTech/winutil/issues/1118#issuecomment-1850868015
