### ISSUE TITLE
Windows Voice typing Not Working

### ISSUE THREAD

**Issue by makhal-sandip** [ChrisTitusTech/winutil#1263]
Windows Voice typing is not working while pressing Windows + H button, 
is showing it is managed by your organisation in settings 

Type windows + H 
Nothing happening

Expected behavior
Starts the windows speech typing panel 

Had to follow this video to fix this 

https://www.youtube.com/watch?v=NRZqnwz4MSQ&t=181s

**Comment by Don-Keballs** [comment]
Can confirm that this is an issue when running the script. Had to re-enable twice now. Thanks for sharing the video link. Would have been massively helpful a few weeks back.

**Comment by KonTy** [comment]
@makhal-sandip @Don-Keballs  the whole purpose of this script is to turn off non essential services so you can free up system resources. Think about it, the script can not read your mind and chose the services that should not be turned off. 

What I would recommend is either not running this script or you can turn off non essential services (**for you**) manually. 

Folding that functionality into the script is not feasible because it will turn into manual process where people will have to pick and chose which services to shutdown.

**Comment by Milor123** [comment]
> Puedo confirmar que se trata de un problema al ejecutar el script. Tuve que volver a habilitarlo dos veces ahora. Gracias por compartir el enlace del vídeo. Habría sido de gran ayuda hace unas semanas.

Could help me? I've used this script but now dont work the Speech with online voices in programs that use SAPI5, dont detect my lenguagues, and when try add voices it crash.

What should I re-activate, what service or what thing? Help guys @KonTy @Don-Keballs
