### ISSUE TITLE
Microwin cannot execute commands

### ISSUE THREAD

**Issue by kangservis** [ChrisTitusTech/winutil#1280]
microwin cannot execute commands,

1. Go to winutil menu
2. Click on microwin section
4. Select your iso
5. execute command
6. and see the error

**Expected behavior**
it works

**Additional context**
I tried it on my personal laptop and microwin runs as expected, only on my pc it happened
![Screenshot (2)](https://github.com/ChrisTitusTech/winutil/assets/153517423/6fa4b873-40f6-4c4c-843e-ca2abb929981)

**Comment by kangservis** [comment]
it seems the image is the problem but i tried 5 different windows iso and have the same errors

**Comment by KonTy** [comment]
@kangservis are all of the images you've tried win10, have you tried win11?

**Comment by madkarmaa** [comment]
been having the same issues here with windows 11 pro

![Screenshot 2023-12-13 190614](https://github.com/ChrisTitusTech/winutil/assets/100418457/c51c3c56-0163-45c8-8228-a13c9f8eabbc)

**Comment by kangservis** [comment]
> @kangservis are all of the images you've tried win10, have you tried win11?

ive tried 
1.w10 22h2
2.w11 23h2
3.w10 enterprise ltsc 21h2
4.w11 22h2
5.w8.1

none of them was working

**Comment by KonTy** [comment]
looking your screenshot, it shows you don't have access to the scratch directory. This might be because the process failed once or was canceled and now it is all messed up. Try deleting c:\microwin and c:\microwinscratch directories manually and try again. Since you've spent so much time debugging this, hope this helps. 

PS At some point I will test win10. We don't support win10 at the moment because it has ESD file not WIM, it should be an easy fix since dism supports both formats I just haven't had time to test it.

**Comment by madkarmaa** [comment]
> looking your screenshot...

I did, nothing changed. I also booted into Linux and removed the folders from there just to be extremely sure, yet the same errors show up.

the errors include: access denied at the directory/file and directory is not empty

PS: choosing to remove Edge will result in even more errors.

**Comment by KonTy** [comment]
In the console when you run this process please find a string and paste here the value of:
``` bash
According to takeown.exe local Yes is 
```
I bet you it is happening due to your local
