### ISSUE TITLE
bug or somthing not sure how to discribe it 

### ISSUE THREAD

**Issue by Dotdk** [ChrisTitusTech/winutil#1340]
the past times il try to update the softwares it comes with this.. 
sidekick where did that come from and how does i get it stop to update it cant find it enywhere in the tool 
and get some fails below in the picture. 
when it install this nothing happens i do the same next time i try 
3 packs have a version numbers that cannot be determined is that the 3 things abow 
sorry il try to understand what it say tryed to find answares on google 
![image](https://github.com/ChrisTitusTech/winutil/assets/6298561/8faa8245-e644-4724-b3ca-a4faa9319541)

**Comment by Dotdk** [comment]
Can see sidekick can i uninstall but when i click got installed and then update installed i getting sideback Agian no clue why

**Comment by Dotdk** [comment]
Have to ask are u guys not getting sidekick everytime u install new updates or is it just me?

**Comment by Dotdk** [comment]
![image](https://github.com/ChrisTitusTech/winutil/assets/6298561/a6681b4c-8a76-455e-bbe3-652be26ef85a)
Did just findt out can it be gigabytes sidekick soft ware there conflict here? so it think sidekick browser is installed but its acturally is gigabytes software it find ?

**Comment by MichTheOcelot** [comment]
well it just looks like you using the gigabyte control center bloatware automatically installs sidekick as a dependency or something, you could probably get rid of it by using something like bulk c uninstaller from the script or getting rid of the control center entirely, then you could just look for a way to prevent gigabyte from installing the bloatware into your system again if it even tries to.

**Comment by Dotdk** [comment]
Mich allright that helped on that now powershell not getting installed and have the 2 lines belov in the picture 
3 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
1 package(s) are pinned and need to be explicitly upgraded.
![image](https://github.com/ChrisTitusTech/winutil/assets/6298561/d302e5ab-e72b-4c26-aa1a-ca74a97973f3)
is there enything i can do about that?

**Comment by MichTheOcelot** [comment]
this might be an issue to report on the Winget repo instead of here since I can't exactly tell if this is the script or not, you can use Winget outside the script to check if it's winutil but just to be practical in reality you need to make sure you didn't uninstall any powershell/appinstaller dependencies when you used bulk c uninstaller. 
try installing a program from the utility to determine that, update does seem to be broken.
that is about all I can help you with. otherwise try reinstalling app installer and other Winget dependencies might help as well.

**Comment by MichTheOcelot** [comment]
this might be an issue to report on the Winget repo instead of here since I can't exactly tell if this is the script or not, you can use Winget outside the script to check if it's winutil but just to be practical in reality you need to make sure you didn't uninstall any powershell/appinstaller dependencies when you used bulk c uninstaller. 
try installing a program from the utility to determine that, update does seem to be broken.
that is about all I can help you with. otherwise try [reinstalling winget](https://www.powershellgallery.com/packages/winget-install/3.2.6) and its dependencies if possible.

**Comment by Dotdk** [comment]
Ty so much for helping think i good it now and i only gave the 3 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results. now 
think we can close this one now
