### ISSUE TITLE
Please add support for the Riot game launcher (League of Legends and Valorant)

### ISSUE THREAD

**Issue by zeonos** [ChrisTitusTech/winutil#1347]
Please add support for the Riot launcher used for Valorant and League of Legends.

it exist as a packages already (linked are the EU versions, there are alternative versions for NA and other regions)

Winget: https://winget.run/pkg/RiotGames/Valorant.EU
Choco: https://community.chocolatey.org/packages/valorant

**Comment by v-Kaefer** [comment]
I'm sorry, but unless there is an actual "**Riot Games Launcher**" winget, that request is kinda impossible. Since there are a lot of regions, we can't choose one to be the "global version" instead of the actual Riot Launcher, that doesn't have a winget.

Because if i decide that the Brazillian one is the global version, i believe 90% of the users/contributors would not agree with me.
If you want an especific region, i believe you can make a request for that region, but i wouldn't be the one to make a pr, since it would most likely be denied...

**Comment by zeonos** [comment]
ok, ill close this request then.
