### ISSUE TITLE
clipgrab

### ISSUE THREAD

**Issue by foolofdestiny** [ChrisTitusTech/winutil#1452]
**Describe the bug**
cant install clipgrab 
not found

manually installed using choco
using pwsh as default in winterm if that makes a difference 

i thought maybe was trying to use winget. 
rg says using choco...

thanks for all  the work. notice alot of change =)

**Comment by KonTy** [comment]
Yes winutil right now doesn't use choco to install apps, we wanted to have choco as afall back in case winget doesn't have a package but that code was never implemented since there is no need for it. @ChrisTitusTech  Whoever added this package never even tested it. I'm not sure how it slipped through the cracks, we should definitely remove it from winutil. 

@ChrisTitusTech I think we need to create a more rigurouse process of accepting apps into winutil. After all it is not an app store and people keep adding so much stuff and half of it doesn't work. :-) I was looking at ways to implement some basic telemetry for app usage but not sure were we could host an endpoint for telemetry. That way you could age out apps that are not used by people.
