### ISSUE TITLE
Heroic launcher should be updated to latest version 2.12.0

### ISSUE THREAD

**Issue by Thedinotamer** [ChrisTitusTech/winutil#1463]
**Is your feature request related to a problem? Please describe.**
I installed the heroic launcher via winutil but was immediately met by an update notification and had to therefore uninstall and install the newest version from their github instead. While writing this I also just remembered that I didn't try to update it via winutil, but at the time I just thought it would just tell me it was updated even if it wasn't.

I'm sorry if this feature request is irrelevant.

**Comment by v-Kaefer** [comment]
It's not irrelevant, but this is more of a tool instead of a program.
It won't keep scanning your system files/programs to see which ones have updates **unless**, you decide to use it!

And it's working just fine with Heroic Launcher, hope this helps!
Here are some screenshots, it's in portuguese, but you can see that it downloads ver 1.9.0 and when i decide to update it, it detects and installs the latest version of it 2.11.0
![Screenshot_19](https://github.com/ChrisTitusTech/winutil/assets/128633407/2e613173-90d8-4707-be41-51e71b0ba49a)
![Screenshot_12](https://github.com/ChrisTitusTech/winutil/assets/128633407/80f1378d-8f95-45fd-81f5-910ebf6a1ecf)

**Comment by theriverlethe** [comment]
This seems like a legitimate issue with winutil. The current version of Heroic on winget is outdated but not THIS old.
