### ISSUE TITLE
Install Tab: Get Installed missed some apps

### ISSUE THREAD

**Issue by sleekspeed22** [ChrisTitusTech/winutil#1488]
**Describe the bug**
On the Install Tab... using the Get Installed button.  Not all apps in the list that are installed on my Windows systems were discovered.  I re-installed WinGet to see if that was the problem but a number of app were missing.  I assume they should be discovered whether or not they were installed through Windows Store or is they are installed on drives other than C:>... It found most app except for Zoom, Joplin, Anaconda, Blender, and GIMP.

**To Reproduce**
1. Open Powershell as Admin
2. run irm christitus.com/win |iex
3. it should default to Install tab... select if it is not selected
4. click on Get Installed button

**Expected behavior**
I expected that any app that is on the list would be discovered if it is installed on this OS (through this OS).  Zoom, Joplin, Anaconda, Blender, and GIMP were missed.  Blender was installed through Steam.

**Screenshots**
App are found when doing a Windows search :
![image](https://github.com/ChrisTitusTech/winutil/assets/78045979/ac1d7e29-3aaf-45be-a8ac-354785c29e39)
![image](https://github.com/ChrisTitusTech/winutil/assets/78045979/5e036789-2ce7-4433-b063-7ff8af91c013)
![image](https://github.com/ChrisTitusTech/winutil/assets/78045979/2d3277e7-1643-4d70-8068-66184c5b5e4b)
![image](https://github.com/ChrisTitusTech/winutil/assets/78045979/655d5deb-fa13-4ae9-ba5c-c4bab0bbf6c5)
Perhaps Blender is working as Designed since it's in Steam
![image](https://github.com/ChrisTitusTech/winutil/assets/78045979/4e7e66ae-584e-461b-8667-9ca6cfa7e593)

**Additional context**
Blender might be working as designed... not sure.

**Comment by v-Kaefer** [comment]
Because it searches the systems programs with `winget list`.
But then it filters the provided list, with all that were installed with `winget`. (last column)

![Screenshot_24](https://github.com/ChrisTitusTech/winutil/assets/128633407/0e755b4c-3d1d-4eb1-925b-42d1dd5c4c17)


- But there could be problems, such as portmaster. That was first implemented with a wrong/deprecated repo and winget.
#1190 [Line-515]

You can verify it, in the official [winget-pkgs repo](https://github.com/wingetbot/winget-pkgs), there is no "`portmaster`" manifest.
https://github.com/wingetbot/winget-pkgs/tree/master/manifests/p

But there is a "**Safing.Portmaster**" manifest, that will be used.
https://github.com/wingetbot/winget-pkgs/tree/master/manifests/s/Safing/Portmaster

So it's those rare cases, but it's not really a bug/faulty feature, it's just a change beyond winutil.
- But once it's reported, it can be fixed!
#1476
