### ISSUE TITLE
The remote name could not be resolved: 'raw.githubusercontent.com'

### ISSUE THREAD

**Issue by Nishant561994** [ChrisTitusTech/winutil#150]
![Untitled](https://user-images.githubusercontent.com/113617198/190435451-076288b6-46ed-489f-a03c-713806e3936b.png)

I have Win 10 21H1. Antivirus and Windows security were disabled.

**Comment by ChrisTitusTech** [comment]
This typically means you have DNS issues or internet connectivity issues. Reboot or connect to a different network and try again

**Comment by Mahaadevan** [comment]
![issue](https://user-images.githubusercontent.com/113818377/190888826-f7a68020-c66c-4b50-8f96-2bea564ec2e1.png)

I had rebooted and tried using a different internet connection but it didnt help.

I don't know wheather this problem is related but i tried to copy and paste just the (https://christitus.com/win) link from the windows toolbox web page which i assumed downloaded the powershell script file and, it only seems to work in the private tor window of Brave browser.

Ps: I was able to use the script fine befere 3 monthe ago without any issues. (last time i used)

**Comment by ChrisTitusTech** [comment]
Very strange I'd be curious to see what dns servers you are using.

**Comment by Nishant561994** [comment]
> ![issue](https://user-images.githubusercontent.com/113818377/190888826-f7a68020-c66c-4b50-8f96-2bea564ec2e1.png)
> 
> I had rebooted and tried using a different internet connection but it didnt help.
> 
> I don't know wheather this problem is related but i tried to copy and paste just the (https://christitus.com/win) link from the windows toolbox web page which i assumed downloaded the powershell script file and, it only seems to work in the private tor window of Brave browser.
> 
> Ps: I was able to use the script fine befere 4 monthe ago without any issues. (last time i used)

Same happened with me. Hyperlinks in Ms Word are not opening. Even if you copy a YouTube url and the paste it in the address bar of any browser in desktop, it wont open. But url and hyperlinks open in mobile. Its called censorship. 
I am using a vpn (Proton bcoz free). Now url, hyperlinks and debloat tool are working.

**Comment by ChrisTitusTech** [comment]
This is definitely some kind of filtering, but the question is what... Why would it target my script? Very strange.
