### ISSUE TITLE
TTL 1.2 issue

### ISSUE THREAD

**Issue by BackinService** [ChrisTitusTech/winutil#159]
when running the command from PowerShell, I kept getting error messages related to the SSL/TTL 

I have had a proxy on this older laptop (CovenantEyes) as a parental control for the children, but that was uninstalled to eliminate that as a possibility.   I turned off (temporarily) the security DNS (AdGuard) at my firewall.

I had reset windows and my network adapters.   Most of the online suggestions were directed at browsers, not powershell.

The only fix I could find (and PowerShell is not my forte) was to add this line, and then the Debloat worked!

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 

I put it in front of the debloat string.

Just a consideration for older laptops that haven't been recently updated or have a parental control (proxy) that may be blocking a https request or consider the debloat string as "dangerous"

Thank you for this program!

**Comment by couleurm** [comment]
I've also seen this issue and same fix with users having the error `The request was aborted Could not create TLS secure channel.` because they were on older Windows builds, one of the solutions is to add it to  your PowerShell profile; there's probably a way to do that via the registry as well.

On a similar note a second longer command to run winutil would be nice to have in the README / wiki in case other people come across this problem

```PowerShell
[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;iex(New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1')
```

**Comment by ChrisTitusTech** [comment]
Just did a commit to test with new documentation @~1

**Comment by BackinService** [comment]
Thank you. Will try it! Awesome app.
