### ISSUE TITLE
Microwin creation successful, but no ISO file

### ISSUE THREAD

**Issue by DRYN07** [ChrisTitusTech/winutil#1592]
The MicroWin creation process finishes without any error, but the "created" ISO does not exist in the destination folder (nor on the whole machine)

Has anyone encountered this?

![image](https://github.com/ChrisTitusTech/winutil/assets/29770761/332af351-496d-417f-98f7-b10551abfff4)

![image](https://github.com/ChrisTitusTech/winutil/assets/29770761/82ebf48e-2041-4557-9a7a-78d45ebe9b14)

**Comment by TechnoHaX** [comment]
Yeah same.. Looking for solution too

**Comment by RescueRangers** [comment]
Just encountered the issue myself, freshly downloaded win11 Polish ISO.

There are no error messages, except when I turn on the option to automatically copy the ISO to Ventoy, then I get an error stating that the ISO does not exist. Otherwise it's just this: `Done. ISO image is located here: C:\Win ISO\Win11.iso` but the ISO is not there.
