### ISSUE TITLE
Wifi not showing

### ISSUE THREAD

**Issue by nishchalrajput22** [ChrisTitusTech/winutil#1634]
i just installed windows 11 home single language microwin ,wifi is missing ,i guess that all services are set to manual maybe idk please help
also most of the services are missing so nothing is working fine

**Comment by og-mrk** [comment]
MicroWin is still considered Buggy and Un-stable, the main devs behind it (@KonTy & @ChrisTitusTech) are still trying to make this Feature more and more stable.
In other words, Using MicroWin to produce Stable ISO Builds of Windows isn't really possible without some bugs with this feature current state, so it isn't recommended to use it Unless you're a Power User and know what you're doing and/or just want to test and try-out the Exported Debloated ISO:
1. on a physical machine (There shouldn't be Drivers issues while installing, but your milage may vary),
2. or inside a VM (Recommended if you're testing a lot, or if you don't have another PC/Laptop laying around, but make sure that you watch Christitus Videos on making one, because there might be some extra steps to make the Installation process as smooth as possible (Drivers and such)).
