### ISSUE TITLE
Winget Woes

### ISSUE THREAD

**Issue by PatrickJnr** [ChrisTitusTech/winutil#1644]
Winget works fine on my machine, but when trying to use it using this tool, I get

![image](https://github.com/ChrisTitusTech/winutil/assets/3267523/46e90861-8a1d-4af2-b21b-77907f04dbd0)

When trying to do a reinstall of Winget  via the tool I get this
![image](https://github.com/ChrisTitusTech/winutil/assets/3267523/1136e882-3700-4d9a-bf27-dc47142fd237)

This is a fresh installation of Windows 11 with the latest patches.

winget -v shows v1.7.3481-preview

I manually updated to the latest via here: https://github.com/microsoft/winget-cli/releases

now it shows v1.7.10514 and winutil seems to see it now.

**Comment by og-mrk** [comment]
This issue is related to chocolatey package manager, rather than a WinUtil issue.
Feel free to post an issue over their community packages repo on Github, to see what can be done to fix this error.

**Note**: Please share the log file for choco (Not Winutil Log File) so people over there can actually help out, it'll be a huge help for them on Diagnosing the source of them issue.

**Comment by MohamedMehrath** [comment]
I got the same problem.
