### ISSUE TITLE
Add Tixati to the Utilities List

### ISSUE THREAD

**Issue by BritishSpuds** [ChrisTitusTech/winutil#1647]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Tixati is a really neat torrenting software i use all the time and i feel like it would work well with this project.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by og-mrk** [comment]
Hello @BritishSpuds, WinUtil uses package managers for installing packages (programs), Currently there's only Chocolatey and Winget, in Chocolatey Community Packages, Tixati (Portable Edition) is available for installation, but Winget doesn't have Tixati, Users back in 2020 & 2021 over on [Microsoft Winget-pkgs](https://github.com/microsoft/winget-pkgs) Repo had tried to add Tixati, but couldn't for Technical Reasons [1](https://github.com/microsoft/winget-pkgs/pull/1560) [2](https://github.com/microsoft/winget-pkgs/pull/31784), So I've made a new package for this program, and it's currently under Azure's Checks (Triggered by Github Actions), and will need a Review from the maintainers, after [this PR](https://github.com/microsoft/winget-pkgs/pull/141322) is merged into main branch, adding Your Requested Package will become possible.

Please note that Contributors can't submit new changes to the Application List, because at the current moment the Project Owner (@ChrisTitusTech) won't accept any, for a number of reason(s) of course.

**Comment by og-mrk** [comment]
Hello @BritishSpuds 
Tixati can be installed using WinGet (The Main Package Manager that WinUtil uses), but like I've previously stated, we currently can't add this app, and any other app to the WinUtil Applications List, because WinUtil is going through a Major Re-Write.
