### ISSUE TITLE
running script with config parameter returns error: Invoke-RestMethod : A parameter cannot be found that matches parameter name 'Config'. 

### ISSUE THREAD

**Issue by zuulmaker** [ChrisTitusTech/winutil#1702]
**Describe the bug**
I'm trying to run the script with my exportet config.json. running the script with config parameter returns error: Invoke-RestMethod : A parameter cannot be found that matches parameter name 'Config'. 

**To Reproduce**
1. run Script, and export config
2. in a fresh install, run the script with the wirtten command: irm https://christitus.com/win -Config "$PSScriptRoot\winutil-config.json" -Run | iex
3. See error

**Expected behavior**
Expected behaviour would be an automated install of software.

**Screenshots**

**Additional context**
tested it on 2 different machines, after fresh install of windows 10.

**Comment by og-mrk** [comment]
This is an Issue with Powershell Cmdlets of `Invoke-RestMethod` (irm) and `Invoke-Expression` (iex), where you can't pass Parameters easily to the downloaded Script, I've looked into this a bit, and [this post from Stack overflow](https://stackoverflow.com/questions/54408925/what-is-shortest-possible-way-to-download-script-from-http-and-run-it-with-param) has some good answer to this particular issue, further reading should be done over there.

What I've found that it's alot easier to download winutil into a `.ps1` file script, then pass into it the argument you might want, of course this's a clunky work around, but this is what I've found to work the best in Reproducible Results (for whatever reason the solutions provided in that Stack overflow post _do work_.. sometime, _and doesn't wanna work most of the time_)

This issue is related to newer ones, which're #1728 & #1729 at the time of writing...

**Comment by og-mrk** [comment]
After a bit of testing, I've found that the shortest version I can do, and it still works fine is the following command:
```powershell
# Download WinUtil Script from christitus.com/win , Then run it through iex with passed argument '-Debug' **Inside** The String
# else (putting '-Debug' outside the string) will be passing '-Debug' Argument to iex Cmdlet itself, which we don't want.
powershell { iex "& { $(irm christitus.com/win) } -Debug" }
# same idea as the above, but we passed '-Config "$PSScriptRoot\winutil-config.json" -Run' instead.
powershell { iex "& { $(irm christitus.com/win) } -Config "$PSScriptRoot\winutil-config.json" -Run" }
```

Further reading can be done [here](https://stackoverflow.com/a/54410144), under section "**Run the script in a child process**"

**Comment by zuulmaker** [comment]
Thanks a lot it worked like a charm.

**Comment by og-mrk** [comment]
> Thanks a lot it worked like a charm.

No problem, glad I could help 👍
Also the example shown in the `README` have been updated, so you confidently reference it in the future, and thanks for reporting this issue @zuulmaker 😄
