### ISSUE TITLE
Update 'Automation' Sub-Section in 'README.md' File

### ISSUE THREAD

**Issue by og-mrk** [ChrisTitusTech/winutil#1767]
### Main Issue
The docs in 'Automation' Sub-Section are all good, until reaching point No. 6 with its command example, this example, doesn't want to work due to several reasons, _mainly because passing Arguments to downloaded script is somewhat a pain in PowerShell, but nonetheless_. Updating the docs with a better/functional example is recommended.

### Why not change it?
The example currently shown is pretty nice, because it's easy to remember and pretty straight forward, that is, if it works properly.
The solution I've found is a bit longer to type/remember, so I've made this issue to discuss if there's a better solution to this issue, Like trying to make the command even shorter, _somehow_, or try another approach.

### The Solution I've Found
The following is something I've found to be working just fine, source is from [this Stack Overflow Answer](https://stackoverflow.com/a/54410144):
```powershell
# Run WinUtil with '-Debug' Parameter
powershell { iex "& { $(irm christitus.com/win) } -Debug" }
# Run WinUtil with '-Config [path-to-your-config] -Run' Paramter
powershell { iex "& { $(irm christitus.com/win) } -Config [path-to-your-config] -Run" }
```

</br>

### Other Issues related to this one
Oldest Issue, which has the detailed explanation on how to fix it, is Issue #1702 .
Other newer Issues are Issue #1728 & #1729 .

**Comment by Marterich** [comment]
I like the solution but if I'm correct, you can simplify the commands even more by removing the enclosing powershell { [...] } call.

``` Powershell
# Run WinUtil with '-Debug' Parameter
iex "& { $(irm christitus.com/win) } -Debug"
# Run WinUtil with '-Config [path-to-your-config] -Run' Paramter
iex "& { $(irm christitus.com/win) } -Config [path-to-your-config] -Run"
```
Regarding the complexity of the statements, I wouldn't worry too much, because the layman would still use the "normal" way of calling winutil and this solution at least provides the user with the possibility to run the script with arguments without having to download it first which is a plus in my book :)
