### ISSUE TITLE
Startup Apps not working !

### ISSUE THREAD

**Issue by Gamelyt** [ChrisTitusTech/winutil#1777]
After running the tool i can't find my startup apps tab in settings, some apps are starting up after boot but most aren't, ive even tried it throught the task manger but no luck !

Here is a screenshot-
![Screenshot 2024-03-31 164923](https://github.com/ChrisTitusTech/winutil/assets/165559699/c861fbcc-1a8c-4824-9af2-ed71c8736514)

**Comment by ChrisTitusTech** [comment]
I've never used the startup apps from the new UI as it always left things out. Have you tried it from Task Manager? (Ctrl+Shift+Esc)
![image](https://github.com/ChrisTitusTech/winutil/assets/7896101/6ef64aa5-f057-4056-b884-4f9af7a23585)

**Comment by YusufKhalifadev** [comment]
@Gamelyt 
What Tweaks did you run ?

**Comment by Gamelyt** [comment]
I did try it from the task manager , after enabling the startup apps, after restarting they would automaticall get disabled.

**Comment by Gamelyt** [comment]
I just run the desktop preset

**Comment by YusufKhalifadev** [comment]
@Gamelyt What version of windows 11 are you using home or pro ?
another suggestion is to try to select desktop preset again and tab on undo tweaks

**Comment by SkylerWallace** [comment]
This is almost likely caused by a group policy. For the sake of documentation, it might be nice to know which group policy causes the startup tab to disappear.

Probably something set here. Ctrl + F 'Policy'
https://github.com/ChrisTitusTech/winutil/blob/main/config/tweaks.json

Unfortunately I don't believe most group policies take affect until after a reboot so this could be annoying to test.
