### ISSUE TITLE
Windows Settings-Home Screen Ads

### ISSUE THREAD

**Issue by vishnurn46** [ChrisTitusTech/winutil#1806]
I'm always frustruated when I open windows settings and then they show try office 365, instal onedrive etc...

These install onedrive card and install office 365 card can be removed from the settings landing page right? some registry hack or something idk..

No alternative 

![image](https://github.com/ChrisTitusTech/winutil/assets/98307777/58de23f2-0cce-42c8-b921-61ea58f8eb0d)
![image](https://github.com/ChrisTitusTech/winutil/assets/98307777/2168856c-bf58-4365-bc6c-a8bc3170776e)

**Comment by ModernTTY** [comment]
I am not sure if these suggestions can be disabled, but when I get the time I will take a look. Anyway good suggestion.

**Comment by SkylerWallace** [comment]
Most of these Setting ads are enabled by the following settings:
Settings > Privacy & security > General > **Show me suggested content in the Settings app**
Settings > Privacy & security > General > **Show me notifications in the Settings app**

Could you check your settings and see if both of these are disabled?

If you use the 'Disable telemetry' tweak in WinUtil, it should turn off most of the offending settings that are responsible for this but it might be missing a couple.

Here is a file from my own repo that contains a bunch of these settings, I believe it has some that are missing from WinUtil:
https://github.com/SkylerWallace/ATOM/blob/main/ATOM/Dependencies/Detectron/Optimizations/Disable%20telemetry.ps1

Running this in an admin PowerShell window should do it (using New-ItemProperty instead of Set-ItemProperty because not all of these exist by default):
```
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-338387Enabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-338388Enabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-338389Enabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-338393Enabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-353694Enabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-353696Enabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-353698Enabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "ContentDeliveryAllowed" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "OemPreInstalledAppsEnabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "PreInstalledAppsEnabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "PreInstalledAppsEverEnabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SilentInstalledAppsEnabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SystemPaneSuggestionsEnabled" -Type "DWord" -Value 0
New-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\SystemSettings\AccountNotifications" -Name "EnableAccountNotifications" -Type "DWord" -Value 0
```

**Comment by vishnurn46** [comment]
![image](https://github.com/ChrisTitusTech/winutil/assets/98307777/1d7a4cac-b482-4f0c-833d-d71041f10b25)

yeah one of the setting [SkylerWallace](https://github.com/SkylerWallace) mentioned was not found, either windows removed it or hidden inside some other menu. the other one was already turned off.
