### ISSUE TITLE
App "Samsung Magician" is very old

### ISSUE THREAD

**Issue by mews-se** [ChrisTitusTech/winutil#1808]
The util wingets version 2-ish, and can't update. From Samsungs website the current version is 8+

Old version cannot detect modern SSD:s for example.

Suggestion to remove the app from the util.

**Comment by og-mrk** [comment]
Hello @mews-se
First of all, thanks for checking out the software listed in WinUtil and provide feedback on if there's an issue with a program of not.
Second, I want to let you know that this isn't the place to request updates to outdated programs, I can see the intent behind your request, but please refer to contacting the maintainer of Chocolatey package for outdated program (that is, if it's outdated, _please check the latest version listed for it_), and requesting a package update in Microsoft's official WinGet Packages Repo, The Repo which contains alot of Metadata that's used to download and install programs, and update them as well, again, if it's outdated in WinGet, you can do this by simply making a new Issue by clicking [this link](https://github.com/microsoft/winget-pkgs/issues/new?assignees=&labels=Help-Wanted%2CPackage-Update&projects=&template=update_request.yml&title=%5BUpdate+Request%5D%3A+), or by going over their Repo > Issues, then click the `new` button to create a new issue.

I know this's a bit of a hassle to do, but you've to understand that WinUtil is simply a script which allows you to install programs USING some available Package Managers (Currently only Chocolatey and WinGet are used/supported), among other things like applying system tweaks and so on...

So in the future, if you find any outdated programs, checkout [this link](https://community.chocolatey.org/packages) and search for that Program Name to findout the chocolatey package, after that click on the correct Chocolatey Package for that program, and click on `Contact Maintainers` to send an Email to all of Maintainers of This Package, follow the on screen instructions and click `Send Message`

### Screenshots
<div align="center">
<img src="https://github.com/ChrisTitusTech/winutil/assets/70659536/924d816e-2bcf-4bc7-b7fe-f4fbb30a1212">
<p><i>Searching for a Program, in this case it's "Samsung Magician"</i></p>
</div>

</br>

<div align="center">
<img src="https://github.com/ChrisTitusTech/winutil/assets/70659536/b99e1b6c-4b1e-42ae-bd1b-b002430282bc">
<p><i>Where to find the "Contact Maintainers" Link</i></p>
</div>

</br>

<div align="center">
<img src="https://github.com/ChrisTitusTech/winutil/assets/70659536/91ca2a9b-5e10-4170-9d9f-83529ece8832">
<p><i>The Form to fill-in to request an update to package, please follow the on-screen instructions.</i></p>
</div>

### Final Notes
The above will look, and is to some extent, a bit too much for alot of people, both in time & effort, in this case, please let us know which programs are outdated, and any experienced developer will take it from here.

Also, Just Letting you know, I've made a PR ([Link to it](https://github.com/microsoft/winget-pkgs/pull/148013)) that updates Samsung Magician, so all should be good with this issue 😄

**Comment by mews-se** [comment]
First of all; wow!

Don't know if it's a template answer or not. But man, this really shows why the OS community is flourishing!
A long reply (with pictures!) that tells the OP to "rtfm" but in a manner that actually is courteous :)

Cheers! And I will most defenitly use the links for choco and winget!

And - btw, don't know if I actually missed it. But this should be a pinned information post for unupdated packages!

**Comment by SkylerWallace** [comment]
WinUtil uses Winget to install programs.
Winget's installer URL to Samsung Magician is the old 4.1 version.
All Winget packages must be able to install silently, Winget is currently not able to install any program that requires user interaction.
Winget's installer URL for Samsung Magician has not been updated to the newer versions because the newer versions of Samsung Magician REQUIRE user interaction to install, it cannot install silently.

Here is Winget's manifest for Samsung Magician which uses a URL for the old 4.1 version:
https://github.com/microsoft/winget-pkgs/blob/master/manifests/s/Samsung/SamsungMagician/4.1.0/Samsung.SamsungMagician.installer.yaml

Here is what happens when somebody tries to update the Samsung Magician manifest to the latest version:
https://github.com/microsoft/winget-pkgs/pull/134001
https://github.com/microsoft/winget-pkgs/pull/148013

@og-mrk Kind of surprised you didn't respond with these details considering you submitted one of these manifest updates xD

**Comment by og-mrk** [comment]
Thanks @SkylerWallace on giving the detailed status update & explanation for this issue , many applications.

> @og-mrk Kind of surprised you didn't respond with these details considering you submitted one of these manifest updates xD

I'll be honest.. I somewhat forgot to give a status update over on this issue, even though I've done this in [this comment](https://github.com/microsoft/winget-pkgs/pull/148013#issuecomment-2045747124). My bad 😅

Sadly, I can't do much to fix this issue @mews-se , due to the reasons highlighted by @SkylerWallace
