### ISSUE TITLE
Phone Link blocked

### ISSUE THREAD

**Issue by joky-greenwood** [ChrisTitusTech/winutil#1810]
I used this utility and i didnt saw option for Phone Link, but now i need to use Phone Link and it says "Some of these settings are managed by your organization". How can i disable this lock? I want to enable Phone Link! 
Please someone help me out! Or what option i have to undo in the Chris Titus utility to make it work.

**Comment by Marterich** [comment]
Most likely the problem is related to the config template for OO Shutup 10. 

At the moment there is sadly no way natively in winutil to undo the changes. 

I revamped the logic to make it a bit easier to work with in PR #1828 and also added the functionality to undo the applied changes, so either you wait and hope the PR gets accepted, or you follow the next steps :)

For now, I would recommend the following steps:
1. Download OO Shutup 10 https://www.oo-software.com/de/shutup10 manually
2. Actions -> Create a system restoration point
3. Actions -> Undo all Changes
4. Actions -> Apply only recommended settings
5. Reboot

This should remove all the policies that were set by the default config of winutil and apply only the recommended (non-functionality breaking) changes provided by oo-software.
I never have encountered any problem with OO Shutup but if anything should now work afterward, you always have your restore point to go back to

Hope this helps

**Comment by Xevion** [comment]
Was dealing with this myself, Phone Link disabled two days after working with winutil and it's built-in OOShutup10, all I had to do was undo the button slider stating 'Disable connecting the PC to mobile devices [...]'.
After that, Phone Link was working again.

I also did the 'undo tweaks' button with 'Disable ConsumerFeatures', I assume that also has to be done too.

Just commenting in-case anyone else finds this discussion and doesn't know the solve.

**Comment by mvpete1** [comment]
Xevion's fix seems to have worked for me. Went into OOShutup10 through CTT and enabled anything that the recommended settings may have disabled (related to mobile devices). I selected 'Disable ConsumerFeatures' and clicked 'Undo Tweaks'. A quick restart and Phone Link was working.
