### ISSUE TITLE
O&O ShutUp10++ shows error when together with Delete Temporary Files

### ISSUE THREAD

**Issue by DiegcD** [ChrisTitusTech/winutil#1822]
**Describe the bug**
When running O&O ShutUp10++ by itself no errors occur but the moment you select it with Delete Temporary Files an error appears on screen and I don't know if the tweaks of ShutUp10++ applies or not, I think it deletes the .cfg config before running O&O on quiet mode.

**To Reproduce**
1. Go to Tweaks Tab
2. Click on Run OO Shutup
3. Click on Delete Temporary Files
4. Click on Run Tweaks
5. Error appears

**Expected behavior**
An O&O ShutUp++ error should not appear.

**Screenshots**
Can't attach due a network error on my end

**Additional context**
Windows 11 updated to today, Spanish MX version

**Comment by ModernTTY** [comment]
> an error appears on screen
Could you copy and paste the error that you got, because without it it is impossible to understand what is going wrong.

**Comment by DiegcD** [comment]
![Captura de pantalla (49)](https://github.com/ChrisTitusTech/winutil/assets/102642718/517f21fa-2d36-404e-8f50-ebc0f8ed6331)

**Comment by Marterich** [comment]
Looks like you encountered a race condition. 
Until now the execution for OO Shutup 10 looked as follows. 

Download EXE -> Download Config -> Run EXE with Config asynchronously
|---files stored in temp folder---------| 

Because the EXE was run asynchronously it technically could happen, that the temp file cleanup task deleted the config file before OO Shutup could load it properly. 

I revamped the OO Shutup logic anyway in #1828 and have also modified the code, so the winutil will now wait until OO Shutup is done applying its changes before continuing on.
