### ISSUE TITLE
Trying to choose a install like VScode and get errors

### ISSUE THREAD

**Issue by Apisit65** [ChrisTitusTech/winutil#1824]
By choosing an app from the list I tried with VScode and Brave to install. After clicking install these error came up.

Version: v1.3.2691
    - Winget is a release version.
    - Winget is Up to Date

Winget is already installed.
Failed in attempting to update the source: winget
Failed when searching source: winget
An unexpected error occurred while executing the command:
0x8a15000f : Data required by the source is missing

No packages were found among the working sources.
===========================================
--      Installs have finished          ---
===========================================
===========================================
--         Winget is installed          ---
===========================================
Version: v1.3.2691
    - Winget is a release version.
    - Winget is Up to Date
Getting Installed Programs...
Done...
===========================================
--         Winget is installed          ---
===========================================
Version: v1.3.2691
    - Winget is a release version.
    - Winget is Up to Date

Winget is already installed.
Failed in attempting to update the source: winget
Failed when searching source: winget
An unexpected error occurred while executing the command:
0x8a15000f : Data required by the source is missing

No packages were found among the working sources.
Failed in attempting to update the source: winget
Failed when searching source: winget
An unexpected error occurred while executing the command:
0x8a15000f : Data required by the source is missing

No packages were found among the working sources.
===========================================
--      Installs have finished          ---
===========================================

**Comment by og-mrk** [comment]
Hello @Apisit65 
your WinGet Package Manager (The program WinUtil Uses, which's used to download and install programs), seems to be outdated. _If I'm not mistaken, which I might be, I think this particular version has a known bug, and it might be the version which ships with windows 10_, anyone more experience can correct me if I'm wrong.

Anyhow, Please refer to [this comment](https://github.com/ChrisTitusTech/winutil/issues/1693#issuecomment-1995937545), which explains how to re-install WinGet to the latest version. Afterward, if the issue is gone, Great! If not, then please provide more information so we can help out.

**Comment by ruxunderscore** [comment]
Interesting I have a check that should have caught this as outdated. I'll have to troubleshoot to see why this happened.

**Comment by Apisit65** [comment]
Ok sounds good!

Ari Gerrits

**Comment by ruxunderscore** [comment]
After a check of the code, I remember what happens with the check there was a bugged version of winget with Win 11 22H2, so that is the version being checked. I can up the minimum version requirement for Winget in the code and that should be a fix in the future for issues like this. Until then, try this and let me know if it fixes your problem: https://github.com/ChrisTitusTech/winutil/issues/1771#issuecomment-2028575684

**Comment by Apisit65** [comment]
Ok will let you know.

Ari Gerrits
