### ISSUE TITLE
Clipboard Win+V

### ISSUE THREAD

**Issue by monitor22** [ChrisTitusTech/winutil#1863]
Please give an option **not to disable** windows clipboard function Win+V

**Comment by og-mrk** [comment]
unfortunately, _at least as far as I know of_, One of WinUtil's Tweaks (Namely the `OO Shutup Tweak`), does this whenever you run it, before the update that was done yesterday, OO Shutup was failing due to a Race Condition (happens when running multiple Tweaks, read about it [here](https://github.com/ChrisTitusTech/winutil/pull/1828) if you're interested), or to put it simply.. It was failing for a few months, ever since OO Shutup team has updated their software.

Now that OO Shutup does work properly, why does it Disable Windows Clipboard History Feature?
... well.. because it can't fully disable The Telemetry Features that Microsoft has installed.. without disabling The Clipboard Feature as well ([Source to previous statement](https://www.reddit.com/r/TronScript/comments/w4g0ue/is_there_a_way_to_reenable_the_clipboard_without/)), and I know it's somewhat of a bummer to use Windows without a Clipboard Manger (at least, like the one that ships with Windows).. but good thing there's Open Source Alternatives that does the same task, _and to some degree_, even better than Microsoft (in terms of Performance/responsiveness, or Advanced feature sets), one good alternative I hear people talk about is CopyQ ([link to their GitHub Page](https://github.com/hluk/CopyQ)).

With that being said, lets say you don't care about that Microsoft is collecting Telemetry Data about you, and you're ok with it (most/all telemetry that comes with Microsoft), in that case, you can select the `OO Shutup Tweak` and then Click the `Undo Selected` button in the bottom left corner of the Tweaks Window, please note that **This Will restore Some Factory Settings**, which you'll have to re-customize some System Settings _again_ (most notable one is your Privacy Settings) and do a re-check to Clipboard History to make sure it's **_enabled_**, which's somewhat annoying to do.. but once you've done it, you can restart your computer and enjoy having your Clipboard Manager back.

> [!NOTE]
> If you can't re-enable Clipboard History Feature after undoing `OO Shutup Tweak`, then restart your computer and see if you can re-enable it (The Clipboard Feature).

**Comment by monitor22** [comment]
Thanks, I will check on the CopyQ
