### ISSUE TITLE
Feature Request: Add Windows 7 Program Installation Support

### ISSUE THREAD

**Issue by djoudx** [ChrisTitusTech/winutil#1868]
Is your feature request related to a problem? Please describe.
The current Windows utility by Chris Titus lacks support for Windows 7, hindering users who specifically need assistance with program installations on this OS.

Describe the solution you'd like
I propose adding a dedicated section within the utility for installing programs on Windows 7 systems.

Describe alternatives you've considered
Manually installing programs on Windows 7 can be tedious; thus, automating this process within the utility would significantly improve user experience.

Additional context
Supporting program installations on Windows 7 would cater to users who rely on this OS, enhancing their workflow efficiency.

**Comment by KonTy** [comment]
Windows 7 security updates support ended on January 14, 2020. We can't support OSes that are not supported by Microsoft. Windows 7 market share is always falling and is under 5% and in order to support it someone will have to spend a lot of time getting it to work. We do WinUtil here for fun in our spare time. 

If you want to look into it and get it working, please submit a PR we will certainly look at it.

**Comment by djoudx** [comment]
Thank you for your response and for your dedication to the project. While I'm not familiar with programming, I'll keep an eye on the project's progress and offer assistance where possible. I appreciate the opportunity to contribute in any way I can.
