### ISSUE TITLE
No more disable uac?

### ISSUE THREAD

**Issue by ahscolan2** [ChrisTitusTech/winutil#1870]
Why yall remove the option to disable UAC

**Comment by Marterich** [comment]
A few releases ago winutil got flagged once again as Malware by Windows Defender.
With the Release 
"Sacrifice to the AV Gods"
Self Elevation and Disable UAC were removed because the functionality ist too similar to what Malware would do so that it would be a constant Cat and Mouse Game to keep winutil working without being detected by AV
