### ISSUE TITLE
Security Concerns about Downloading & Requesting of The Windows Utility Script

### ISSUE THREAD

**Issue by og-mrk** [ChrisTitusTech/winutil#1873]
### Some Background

I was chilling and watching some Linux Content on a calm Wednesday Night (because why you wouldn't you lol), and it's by the legend himself, [Brodie Robertson](https://www.youtube.com/@BrodieRobertson), and this video that came to my attention is titled "This ZSH Plugin Manager Is Really SUS", here's [a youtube link](https://www.youtube.com/watch?v=pHVbjLTFmVo) for the video.

and while reading the comment section of that video, I noticed something odd... "Isn't running WinUtil is similar to the method used to initialize/run zi (the "Suspicious Open Source" discussed in the video)?"

.. and it turns out my concerns were unfortunately right, both are very similar to how they ran.

### The Security Concern in question

> [!NOTE]
> I'll be discussing in the security concerns behind the "URL In-directing" feature when doing `irm christitus.com/win | iex`, which's used to download & run WinUtil

One of the comments in [this video](https://www.youtube.com/watch?v=pHVbjLTFmVo) highlighted a potential abuse of this URL In-directing method, like having a DNS Hijack for example, or a Hacker/Bad Actor Takes Ownership of the `christitus.com` website, or just the `/win` routine, where your requested URL can be re-directed to something you didn't want to run, like a malicious PowerShell Script, which can change/steal/damage the User's Personal Computer & Information (whether it's a PC, Laptop, or even Windows Tablet for that matter).. this got me worrying really on the potential security risks behind the continuation of using this method.

### Screenshots showing that it does a URL Re-direct

![image](https://github.com/ChrisTitusTech/winutil/assets/70659536/1db58d48-d630-4868-8950-aa19d2989a2c)

![image](https://github.com/ChrisTitusTech/winutil/assets/70659536/f8853c4f-15a9-4494-8b91-12dbfb8d534c)

### Possible Solutions to Mitigate these risks

We'll need to lessen the current points of failure, like the possibility of Chris's website being Hacked/Hijacked by a Bad Actor, and the other (a less likely risk, as it'll depend on your local network security) is a DNS Hijack.

I personally am not a Professional/Expert in the field of Cybersecurity, Penetration testing and such, so please take the above with a grain of salt, plus if the above concerns of mine is really unnecessary, because of "X, Y, and Z", then my bad for wasting your time reading this Issue, and hope you've a nice day 😄

**Comment by ChrisTitusTech** [comment]
I've been in IT Infrastructure for over 20 years and purchased christitus.com back in 2009. I generally renew the domain in 10 year chunks, but I never let it get close to expiring. So loss of ownership won't happen. 

From a threat perspective or website hack... everything is done using HUGO and static sites. This means there is no database or threat surface to hack. Most websites today do use WordPress or LAMP stacks, but I took a different approach because I've seen these hacks firsthand and why my site operates the way it does. You can't hack something that doesn't accept any input or have an entry point. All redirects are done from the DNS host level and not local files like htaccess or db redirects like other sites.

The final concern is the registrar or DNS host. I use Cloudflare which is the worldwide leader and not some mom-and-pop setup. Most big businesses, banks, etc. use this service and other targets that would be of higher importance than my site if it were to be compromised. Login information is isolated and 2FA is done at every level. 

Nothing is unhackable, but I've taken precautions to protect myself from attack as much as possible. It would be much easier to infiltrate a large organization or even a bank than to breach christitus.com.
