### ISSUE TITLE
Not picking up installed apps

### ISSUE THREAD

**Issue by gjblajian** [ChrisTitusTech/winutil#1917]
**Describe the bug**
I have numerous apps installed that are listed in the Install tab of the GUI but when I click on Get Installed they are not detected.  Here are a few examples: Thorium, Discord, NodeJS, Eclipse, LibreOffice, .NET Desktop Runtime 8, NuGet, OneDrive, Paint.NET, there may be more but those are the ones I am sure are installed and not getting picked up.

I also noticed that when I selected "Upgrade All" the upgrade failed on several. I know that this is a difficult item to overcome but some options to correct the issues might be a nice to have. It may be nice to have an intermediate screen to deselect items you do not want to try to upgrade. And an indicator to show if there is an upgrade available. I know ChocolateyUI and WingetUI, let you know and SORT OF give you options to overcome them, though neither works particularly well.

![image](https://github.com/ChrisTitusTech/winutil/assets/5183939/9f4e06d4-24a8-4c79-8663-e5baf9429d8c)
![image](https://github.com/ChrisTitusTech/winutil/assets/5183939/b190a433-b82b-43a4-95ce-ff7cf5a7f77d)

WinGetUI probably works slightly better than ChocolateyUI (it is definitely more informative when it fails). But neither really updates particularly well. Not even as well as their command line counterparts.

**To Reproduce**

**Expected behavior**
If the application is installed when the "Get Installed" button is pushed I would expect it to be detected.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/5183939/bcae740c-15ae-40e1-8e47-affcfe12720c)

**Additional context**
I know I included a little more data that was unrelated to the issue but I wanted you to be aware of the similar tools you are "competing" against.

**Comment by v-Kaefer** [comment]
> I have numerous apps installed that are listed in the Install tab of the GUI but when I click on Get Installed they are not detected.

Winutil is a pure winget+chocolatey. You can confirm this with your own screenshots, none of the programs you listed, show on either WingetUI nor ChocolateyUI. That's because, the same way winget install programs on your pc, with the default folders, it searches for them the same way. So for example, if the default is "C:\Users\User\Documents", and you have programs that you installed "outside"/not using winutil/winget/chocolatey, and changed their folder to "C:\Users\User\Docs", it **won't be found**.

> I also noticed that when I selected "Upgrade All" the upgrade failed on several. I know that this is a difficult item to overcome but some options to correct the issues might be a nice to have.

Again, totally based on winget and chocolatey. If it has a problem, it's either their repo download that's broken, or winget. If winutil has that kinda problem, it might aswell not even work, instead of give you an error lol

> And an indicator to show if there is an upgrade available.

The idea behind winutil, is to give **YOU** power over what **YOU** want to do, **WHEN** you want to do, with your pc/programs. If you want a program that reminds/warns you of an available update as soon as its out, **winutil is not it**.

> It may be nice to have an intermediate screen to deselect items you do not want to try to upgrade.

You just need to unselect the programs you do not want to update, then it won't try to update it.

> I know I included a little more data that was unrelated to the issue but I wanted you to be aware of the similar tools you are "competing" against.

This should be answered by Chris himself, but since I'm answering you, I'll just say that, I believe there is NO competition, since as I said before, winutil is just a pretty, restructured, winget + chocolatey face.

**Comment by ruxunderscore** [comment]
Installing programs is primarily handled by Winget within winutil, as far as I have been able tell. Winget is a very imperfect product, and isn't as mature as something like Apt in Debian/Ubuntu distros–which means it also lacks some features of the aforementioned Linux package manager. Therefore, some programs aren't detected as well as others, while some can be detected as different programs in within Winget's repo. This can lead to the installing of a program you didn't have before. Again, it's all comes down to it's imperfect nature.
