### ISSUE TITLE
Cleanup WindowsApps folder, a WinUtil Challenge?

### ISSUE THREAD

**Issue by robsiera** [ChrisTitusTech/winutil#1977]
**Is your feature request related to a problem? Please describe.**
In windows 11 (probably earlier too) there a protected folder C:\Program Files\WindowsApps. It holds the Apps but does not cleanup the old version, ever.
![image](https://github.com/ChrisTitusTech/winutil/assets/5709726/e5fb12c7-8f98-47c2-99b1-b2dbeaeffed7)

**Describe the solution you'd like**
Remove obsolete versions/folders/files

**Describe alternatives you've considered**
ignore the waist of space

**Additional context**
It has been said that this is (almost?) impossible to accomplish. :-)
https://www.tenforums.com/performance-maintenance/185009-how-clean-up-windowsapps-folder.html#post2294527

**Comment by Marterich** [comment]
I would recommend posting this as an Idea in the Discussion area of the Repo because this would be a new feature and issues are closed after 2 weeks of inactivity. 
Seeing this is kind of a big task to implement and it will take a lot of trial and error as well as potential error handling I can see this taking longer than two weeks.

In general, I think this is a cool Idea, but as you already said, quite tricky to implement/execute, especially fully automated

**Comment by robsiera** [comment]
As suggested by @Marterich , better react in [this discussion thread](https://github.com/ChrisTitusTech/winutil/discussions/1983).
