### ISSUE TITLE
Explain MicroWin Process More

### ISSUE THREAD

**Issue by mattvisa** [ChrisTitusTech/winutil#2028]
**Is your feature request related to a problem? Please describe.**
I am fairly knowledgable, but not an absolute expert. In modifying a Windows ISO with the MicroWin feature, it would really help to have some additional explanation for what each item does.

**Describe the solution you'd like**
I would like to see an asterix on each step. For example, under "Download oscdimg.exe from CTT Github", you might add a little bit about what this does and that you have to click this to download it to your machine to run the MicroWin service the first time.

What is "Scratch Dir". What does "ISO location will be printed here" mean? I assume it's the output location, but not sure. 

Choose Windows SKU might be better displayed as a list with check marks so that the user knows to click through that next.

The Micro Win features, ie, the list that starts with - Remove Telemetry and Tracking, might be put in the same order as the list for "Choose Windows features you want to remove from the ISO". On that same note, a popup explanation fo the "Keep Provisioned Packages" and the "Keep Appx Packages" would be helpful because I don't know what they are. 

Lastly, Copy to Ventoy might be removed completely and replaced with the output file location. I also wonder if you want to automatically append a FileName_debloat to the output file naming structure so that you don't overwrite the original ISO. 

**Describe alternatives you've considered**
Not applicable

**Additional context**
None

**Comment by mattvisa** [comment]
Also, when I completed the debloat process, it finished with quite a few errors and told me the process failed. But it actually saved the updated ISO file, and I am using it now on a PC and it's working fine.

**Comment by mattvisa** [comment]
Here are some of the errors. This likely is user error because I did not save the file properly to Ventoy, etc. 

Exporting image into C:\Users\mattv\AppData\Local\Temp\Microwin_20240604_141808_3775\sources\install2.wim
Invoke-WPFMicrowin : An unexpected error occurred: Unable to load DLL 'unattend.dll': The specified module could not
be found. (Exception from HRESULT: 0x8007007E)
At line:2805 char:24
+         "WPFMicrowin" {Invoke-WPFMicrowin}
+                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-WPFMicrowin

Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Unmounting image...
Dismount-WindowsImage : The request is not supported.
At line:4040 char:9
+         Dismount-WindowsImage -Path $scratchDir -Save
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Dismount-WindowsImage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.DismountWindowsImageCommand

Creating ISO image
[INFO] Using oscdimg.exe from: oscdimg.exe
Copying target ISO to the USB drive
Copy-Item : Cannot overwrite the item D:\Win11_23H2_English_x64v2_debloat.iso with itself.
At line:1035 char:4
+             Copy-Item -Path $fileToCopy -Destination $destinationPath ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\Win11_23H2_English_x64v2_debloat.iso:String) [Copy-Item], IOException
    + FullyQualifiedErrorId : CopyError,Microsoft.PowerShell.Commands.CopyItemCommand

File copied to Ventoy drive D
Done Copying target ISO to USB drive!
 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)
ISO creation failed. The  C:\Users\mattv\AppData\Local\Temp\Microwin_20240604_141808_3775  directory has not been removed.

**Comment by ChrisTitusTech** [comment]
This should now be fixed in #2030

**Comment by tecworks-dev** [comment]
Getting image information f:\Downloads\winutl-scratch\micro\sources\install.wim
Finding suitable Pro edition. This can take some time. Do note that this is an automatic process that might not select the edition you want.
Selected value '6 : Windows 11 Pro'.....
Done reading and unpacking ISO

*********************************
Check the UI for further steps!!!
Target ISO location: f:\Downloads\windows_11_23h2_winutils.iso
Index chosen: '6' from 6 : Windows 11 Pro
Mounting Windows image. This may take a while.
Invoke-WPFMicrowin: F:\downloads\winutil.ps1:3775
Line |
3775 |          "WPFMicrowin" {Invoke-WPFMicrowin}
     |                         ~~~~~~~~~~~~~~~~~~
     | An unexpected error occurred: The volume of the specified mount path does not support reparse points.  Please
     | mount to a volume that supports reparse points.
Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Cleaning up image...
Cleanup complete.
Unmounting image...
Dismount-WindowsImage: F:\downloads\winutil.ps1:4949
Line |
4949 |          Dismount-WindowsImage -Path "$scratchDir" -Save
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The request is not supported.
Exporting image into f:\Downloads\winutl-scratch\micro\sources\install2.wim
Remove old 'f:\Downloads\winutl-scratch\micro\sources\install.wim' and rename f:\Downloads\winutl-scratch\micro\sources\install2.wim
Windows image completed. Continuing with boot.wim.
Mounting boot image f:\Downloads\winutl-scratch\micro\sources\boot.wim into f:\Downloads\winutl-scratch\Scrach
Invoke-WPFMicrowin: F:\downloads\winutil.ps1:3775
Line |
3775 |          "WPFMicrowin" {Invoke-WPFMicrowin}
     |                         ~~~~~~~~~~~~~~~~~~
     | An unexpected error occurred: The volume of the specified mount path does not support reparse points.  Please
     | mount to a volume that supports reparse points.
Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Unmounting image...
Dismount-WindowsImage: F:\downloads\winutil.ps1:5011
Line |
5011 |          Dismount-WindowsImage -Path "$scratchDir" -Save
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The request is not supported.
Creating ISO image
[INFO] Using oscdimg.exe from: C:\Users\m_a_s\AppData\Local\Temp\oscdimg.exe

OSCDIMG 2.56 CD-ROM and DVD-ROM Premastering Utility
Copyright (C) Microsoft, 1993-2012. All rights reserved.
Licensed only for producing Microsoft authorized content.


Scanning source tree (500 files in 43 directories)
Scanning source tree complete (945 files in 86 directories)

Computing directory information complete

Image file is 6306136064 bytes (before optimization)

Writing 945 files in 86 directories to f:\Downloads\windows_11_23h2_winutils.iso

100% complete

Storage optimization saved 4 files, 24576 bytes (0% of image)

After optimization, image file is 6308212736 bytes
Space saved because of embedding, sparseness or optimization = 24576

Done.
OSCDIMG Error Level : 0
 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)


Performing Cleanup...
Done. ISO image is located here: f:\Downloads\windows_11_23h2_winutils.iso
Bye bye!
