### ISSUE TITLE
RDP disabled after executing the script, PCs are  no longer accessible via RDP

### ISSUE THREAD

**Issue by JuRo1971** [ChrisTitusTech/winutil#2082]
**Describe the bug**
Hi Chris, obviously you did some changes in the tweaks section. After executing the script with standard settings and rebooting these PCs, these PCs are  no longer accessible via RDP. Checking the RDP settings on these PCS, they were disabled. This was reproduced on 2 Winn 11 machines and one Win machine. 

**To Reproduce**
1. Start script
2. Set standard settings
3. Execute Script
4. reboot
5. Try to connect the PC from another PC
6. Connection fails
7. Checking RDP Settings > disabled > enabled before executing the script

**Expected behavior**
RDP is up and running after executing the script or please answer which button lead to this behaviour

**Screenshots**

**Additional context**

Thanks for your great work
Greetings JuRo

**Comment by Marterich** [comment]
This is due to a Change in the "Recommended" Tweaks by OO-Shutup. 
OO-Solutions keeps changing its recommendations every now and then and to keep winutil maintainable we opted to apply all OO recommendations without any customization. 

To undo the change: 
1. Click "Customize OO Shutup Tweaks" under Advanced Tweaks
2. Click on the "Local Machine" Tab
3. Search for "Disable remote connections to this computer"
4. Disable the tweak
 
Afterwards, you should be all set :)

**Comment by JuRo1971** [comment]
ahh ok, thanks, I will try

**Comment by Marterich** [comment]
@JuRo1971 Please close the issue yourself (Button right beside Comment), as Chris is the only one who has the permission to close issues and otherwise the issue would stay vacant for 14 days until the action runs :)

**Comment by JuRo1971** [comment]
Closed
