### ISSUE TITLE
Adobe DeBloat and Adobe Network Block Breaks All Adobe

### ISSUE THREAD

**Issue by mattvisa** [ChrisTitusTech/winutil#2107]

**Comment by MyDrift-user** [comment]
Hey there, thanks for the Report. I am the creator of the two Tweaks you've mentioned and sorry for the issues you are having.

For context, the Adobe Tweaks are under "Advanced Tweaks - CAUTION" because most of it's tweaks can and will break things. 

Adobe Network Block literally blocks connections to many adobe servers. The Creative Cloud Application will most likely not run, but the rest of Application Suite should run fine (also access to files saved in Adobe Cloud).
If you want to use "Creative Cloud Desktop" in any way you have to undo the Network Block.

I've updated my Adobe Software and ran the tweaks againg but was not able to reproduce the issue u mentioned.
Also undoing the Tweaks did really undo everything that it has done.

Applications used for testing on my end:
- Adobe Creative Cloud > Failed Start with enabled network blocking as expected
- Adobe Photoshop 2023 > worked
- Adobe Photoshop 2024 > worked
- Adobe Premiere Pro 2024 > worked
- Adobe Acrobat > worked
- Adobe Reader > worked

Could you please provide more info that you may have gotten when starting a product?
"I had to search out the file changes and rename/delete them." Could you also please mention what you have done to make it work again? With that info i can hopefully find and fix the issue.

**Comment by mattvisa** [comment]
Hey, no sweat at all. I totally understand on the section where it was listed. I want this to block the telemetry to Adobe and the annoying notifications!

For context, I have installed most of the CC apps but tried to use only Premiere, Photoshop, and Illustrator and all failed to launch after running the tweak originally. 

Unfortunately, I reverted the changes so I can't screenshot the error; essentially, whenever I opened an Adobe CC product, it told me that it couldn't connect to verify that my account was active (where they make you login and register a computer). I got an error message saying they couldn't connect to the Adobe servers (obviously due to the fact that it was blocked in the host file).

When you say "undoing the tweaks" I didn't see that in the CTT tool as an option (maybe it can get added as an option to select in the tool, unless it's there and I missed it). 

I tried to run the undo code just through Power shell, ie: 

`"UndoScript": [
      "
      function RestoreCCService {
        $originalPath = \"C:\\Program Files (x86)\\Common Files\\Adobe\\Adobe Desktop Common\\ADS\\Adobe Desktop Service.exe.old\"
        $newPath = \"C:\\Program Files (x86)\\Common Files\\Adobe\\Adobe Desktop Common\\ADS\\Adobe Desktop Service.exe\"
    
        if (Test-Path -Path $originalPath) {
            Rename-Item -Path $originalPath -NewName \"Adobe Desktop Service.exe\" -Force
            Write-Host \"Adobe Desktop Service has been restored.\"
        } else {
            Write-Host \"Backup file does not exist. No changes were made.\"
        }
      }

      function AcrobatUpdates {
        # Default Value:
        # 3 = Automatically download and install updates
    
        $rootPath = \"HKLM:\\SOFTWARE\\WOW6432Node\\Adobe\\Adobe ARM\\Legacy\\Acrobat\"
    
        # Get all subkeys under the specified root path
        $subKeys = Get-ChildItem -Path $rootPath | Where-Object { $_.PSChildName -like \"{*}\" }
    
        # Loop through each subkey
        foreach ($subKey in $subKeys) {
            # Get the full registry path
            $fullPath = Join-Path -Path $rootPath -ChildPath $subKey.PSChildName
            try {
                Set-ItemProperty -Path $fullPath -Name Mode -Value 3
            } catch {
                Write-Host \"Registry Key for changing Acrobat Updates does not exist in $fullPath\"
            }
        }
      }

      RestoreCCService
      AcrobatUpdates
      "
    ],
    "service": [
      {
        "Name": "AGSService",
        "StartupType": "Disabled",
        "OriginalType": "Automatic"
      },
      {
        "Name": "AGMService",
        "StartupType": "Disabled",
        "OriginalType": "Automatic"
      },
      {
        "Name": "AdobeUpdateService",
        "StartupType": "Manual",
        "OriginalType": "Automatic"
      },
      {
        "Name": "Adobe Acrobat Update",
        "StartupType": "Manual",
        "OriginalType": "Automatic"
      },
      {
        "Name": "Adobe Genuine Monitor Service",
        "StartupType": "Disabled",
        "OriginalType": "Automatic"
      },
      {
        "Name": "AdobeARMservice",
        "StartupType": "Manual",
        "OriginalType": "Automatic"
      },
      {
        "Name": "Adobe Licensing Console",
        "StartupType": "Manual",
        "OriginalType": "Automatic"
      },
      {
        "Name": "CCXProcess",
        "StartupType": "Manual",
        "OriginalType": "Automatic"
      },
      {
        "Name": "AdobeIPCBroker",
        "StartupType": "Manual",
        "OriginalType": "Automatic"
      },
      {
        "Name": "CoreSync",
        "StartupType": "Manual",
        "OriginalType": "Automatic"
      }
    ]
  },`

and also: 

` "UndoScript": [
      "
      # Define the local path of the HOSTS file
      $localHostsPath = \"C:\\Windows\\System32\\drivers\\etc\\hosts\"
      
      # Load the content of the HOSTS file
      try {
          $hostsContent = Get-Content $localHostsPath -ErrorAction Stop
      }
      catch {
          Write-Error \"Failed to load the HOSTS file. Error: $_\"
          return
      }
      
      # Initialize flags and buffer for new content
      $recording = $true
      $newContent = @()
      
      # Iterate over each line of the HOSTS file
      foreach ($line in $hostsContent) {
          if ($line -match \"#AdobeNetBlock-start\") {
              $recording = $false
          }
          if ($recording) {
              $newContent += $line
          }
          if ($line -match \"#AdobeNetBlock-end\") {
              $recording = $true
          }
      }
      
      # Write the filtered content back to the HOSTS file
      try {
          $newContent | Set-Content $localHostsPath -Encoding ASCII
          Write-Output \"Successfully removed the AdobeNetBlock section from the HOSTS file.\"
      }
      catch {
          Write-Error \"Failed to write back to the HOSTS file. Error: $_\"
      }
      
      # Flush the DNS resolver cache
      try {
          Invoke-Expression \"ipconfig /flushdns\"
          Write-Output \"DNS cache flushed successfully.\"
      }
      catch {
          Write-Error \"Failed to flush DNS cache. Error: $_\"
      }
      "
    ]`

But, I ended up manually going in and renaming C:\\Program Files (x86)\\Common Files\\Adobe\\Adobe Desktop Common\\ADS\\Adobe Desktop Service.exe.old back to C:\\Program Files (x86)\\Common Files\\Adobe\\Adobe Desktop Common\\ADS\\Adobe Desktop Service.exe and clearing out the host file back to normal because running the above scripts threw up errors for me. I don't know if the startup is back running or not, but that's fine with me if it doesn't run at startup.

I read through the code that was included and see how it blocks sites by pulling from the Github website list. I think that may be the main issue that some(one) of those URLs may be necessary to validate actual accounts.

**Comment by MyDrift-user** [comment]
> When you say "undoing the tweaks" I didn't see that in the CTT tool as an option (maybe it can get added as an option to select in the tool, unless it's there and I missed it).
> 

With "undoing the tweaks" i meant selecting the tweaks and pressing the "undo selected tweaks" button. it is at the bottom so you may have to scroll to see it. A fix for that would be to make the do and undo buttons fixed so they are always shown.

Also for loggins it is required to connect to those servers from the list, so if you have to update/login the Adobe network block can't be enabled.

**Comment by mattvisa** [comment]
Ah, understood. I wonder if you might make a pull request to update the verbiage for the use case, then. I imagine that the use case would be for folks using older versions of Adobe that would not require (or want) being connected to the CC. If that is the use case, in the hover over description, maybe add something that says "Not for use with systems with active Adobe Creative Cloud subscriptions. Only meant for use with standalone versions of Adobe software that are no longer updated or maintained by Adobe." Otherwise, folks like me who want to stop being pestered by Adobe notifications BUT need to use their syncing won't download it mistakingly thinking it's remedial and not nuclear.

**Comment by MyDrift-user** [comment]
Thank you for your suggestion. The "Adobe Network Block" tweak is intended for advanced users who understand the implications of their actions (therefore in the advanced tweaks section). Typically, users start Adobe applications directly rather than through the Creative Cloud Desktop Application, so this tweak should not pose a problem for simply using most of their services. If network access is required or you simply want to use the Adobe Creative Cloud Application, the "Adobe Debloat" tweak does not Block the Network access and seems to be more to your liking.

The name "Adobe Network Block" is quite self-explanatory. Additionally, any changes made can be easily undone using the "Undo Selected Tweaks" button, therefore, adding more warnings would diminish the significance of the Advanced Tweaks section.

If you still believe that changing the verbiage is necessary, you are welcome to create a pull request. You can fork this repository, make the changes you propose, and submit a pull request comparing your fork with the main branch of WinUtil.

**Comment by mattvisa** [comment]
I do not use CC to start any apps at all ever. But it blocked independent usage completely for me. It blocked photoshop, illustrator, and premiere on two bare metal installs and one vm. 

I understand advanced tweaks but not when it breaks functionality completely. I don't understand the use case for this being included even under advanced settings. I want to block telemetry and useless notifications, not block the apps from running. I'll leave this here. I'm no developer nor will I submit a pull request. I just thought it would be helpful to share feedback. Please feel free to ignore the feedback. But this just bricked individual adobe apps for me on 3 separate windows installs.
