### ISSUE TITLE
`Get-CimInstance` and `Stop-Transcript` errors on WinUtil from PowerShell v7.4.3 (Windows 11 23H2)

### ISSUE THREAD

**Issue by charlescgs** [ChrisTitusTech/winutil#2124]
**Describe the bug**
Script launches, but produce and error message during both launch and exit.

**To Reproduce**
1. Start elevated PowerShell 7 instance.
2. Type script init command: 'irm.. etc'.
3. See the error.
4. Close script window.
5. See another error.

**Expected behavior**
Should not show an error message.

**Screenshots**
#### Startup error msg:
![image](https://github.com/ChrisTitusTech/winutil/assets/135472912/82e700cc-d994-4902-8c51-a584f6ef6f31)

#### Exit error msg:
![image](https://github.com/ChrisTitusTech/winutil/assets/135472912/fd16bcbe-2a1a-46f0-952a-b8ae56a2ae29)

**Comment by charlescgs** [comment]
Unfortunately yes..
![image](https://github.com/ChrisTitusTech/winutil/assets/135472912/24bc8ca7-cad4-4508-b785-4a6f1a65ee59)

**Comment by MyDrift-user** [comment]
It looks like your shell is the issue here, and not the WinUtil itself.

I would suggest following steps forward:
- trying that command again in Windows Powershell (the blue one), wont help but may clarify something.
- update powershell 7 if possible and try again
- look at forums that have same/similar issues
- if nothing helps: uninstall, restart client & reinstall powershell 7

I was looking at some forums and this issue might occur if you install powershell in a custom location. if that is the case try not setting a custom location at install and try again.

**Comment by charlescgs** [comment]
@MyDrift-user I just remembered I have A bit toned down PS profile:
`$PSModuleAutoLoadingPreference = 'None'

Import-Module Microsoft.PowerShell.Utility
Import-Module Microsoft.PowerShell.Management

Invoke-Expression (&starship init powershell)`

I did it as loading a profile was taking too long.
Could it be that I am missing a module?

**Comment by MyDrift-user** [comment]
Yes

Module for Transcripts: Microsoft.PowerShell.Host
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.host/?view=powershell-7.4

Module for Get-CimInstance: CimCmdlets
- https://learn.microsoft.com/en-us/powershell/module/cimcmdlets/?view=powershell-7.4

**Comment by charlescgs** [comment]
Thanks a lot!
I added those two modules to my profile and now both commands are working and WinUtil shows no errors.
