### ISSUE TITLE
OnDrive removal issues.

### ISSUE THREAD

**Issue by charlescgs** [ChrisTitusTech/winutil#2125]
**Describe the bug**
OneDrive is not being totally removed after running `Remove OneDrive` tweak.
Program still shows in app list, in `winget upgrade` and in the Explorer as not-removable pinned shortcut.
Also while running a tweak an error pops-up.

**To Reproduce**
1. Run `Remove OnDrive` tweak.
2. Check explorer, App List in Settings and winget list.
3. See the OneDrive there.

**Expected behavior**
Tweak should not error and after it OneDrive should be gone for good.

**Screenshots**
## Run it:
![image](https://github.com/ChrisTitusTech/winutil/assets/135472912/67397464-ac04-42ad-973f-b92f6af0d82a)

## See the error:
![image](https://github.com/ChrisTitusTech/winutil/assets/135472912/1cc11abf-fd4b-40b9-a151-dee7899bc7e9)

## Explorer:
![image](https://github.com/ChrisTitusTech/winutil/assets/135472912/d3269fa6-d112-41f1-b230-f2dd15ce7746)

## App List:
![image](https://github.com/ChrisTitusTech/winutil/assets/135472912/bdf7b064-4b79-42ef-81e2-1a74bff73571)

## WinGet upgrade:
![image](https://github.com/ChrisTitusTech/winutil/assets/135472912/8121be2f-6d6b-40ff-bce6-54ac2cca5d5d)

**Comment by og-mrk** [comment]
Hello @charlescgs 
First of all, thanks for reporting this issue, so that contributors get informed of such edge cases we didn't have the opportunity to replicate.

Now, looking at the screenshots you'vs shared, two things come to my attention..
1. Robocopy (a CLI tool this tweak uses) has failed for some reason, giving an Access Denied error when trying to copy the OneDrive folder found in the User's Home Directory.. maybe because the folder owner has been set to something the script hasn't anticipated/excepted.
2. As far as I can remember (_not sure, maybe someone can correct if I'm wrong_), is that this tweak uses WinGet (a package manager used in Windows, and is used in multiple places in WinUtil).. for whatever reason, it couldn't find a way to uninstall OneDrive. Hence the second error shown in red color indicates it has failed (**Application not found**).. There isn't a fallback for this case, so OneDrive hasn't been uninstalled from your system after running the OneDrive Tweak.

Unfortunately, I don't have the time to figure out solution(s) for the above problems. Maybe someone more experienced can take this issue to come up with a good solution.

**Comment by Marterich** [comment]
@og-mrk 
Part of the robocopy problem could be that winutil seems to expect the Ondedrive folder to reside inside the user folder. 
I'd recommend using $ENV:OneDrive instead as this variable should hold the actual location. 

Another problem that I encountered when playing around with Onedrive stuff is, that robocopy isn't able to move "Cloud Only" Files that are only linked on disk so maybe there is some work to be done to either make sure every file is downloaded before trying to move them or to filter them somehow. 

Also I think some work needs to be done to "cleanup" after a Onedrive install (e.g the registry key: Computer\HKEY_CURRENT_USER\Software\Microsoft\OneDrive) as OneDrive cannot be reinstalled afterward because it thinks it's already there.

**Comment by Marterich** [comment]
@charlescgs @og-mrk 
I created a PR that most likely will fix the described Issues

**Comment by charlescgs** [comment]
Thanks @og-mrk for the reply.
Checked `C:\Users\CG` directory and OneDrive folder does not exist there.
But OneDrive is still in all places I screenshooted earlier.
@Marterich When I am using `$ENV:OneDrive`, the location matches user folder.

**Comment by og-mrk** [comment]
It's interesting how the Environment Variable is pointing to a non-existing folder. Should we add a check to make sure OneDrive Folder exists or not in PR #2155 ? @Marterich

**Comment by Marterich** [comment]
> It's interesting how the Environment Variable is pointing to a non-existing folder. Should we add a check to make sure OneDrive Folder exists or not in PR #2155 ? @Marterich 

I'm not quite sure. I think this is most likely the result of the failed uninstallation, which shouldn't occur again when using the local executable for the uninstallation. 

In the case of @charlescgs I think a clean reinstall of OneDrive with a clean uninstallation using the new script should resolve the problems. (It might be, that you have to delete a OneDrive registry key manually to be able to reinstall after a failed uninstallation but the process is documented by Microsoft)

**Comment by og-mrk** [comment]
> Edit: @og-mrk I mean we could technically try also handling broken one drive installations but I think this is a bit much for the time being 

@Marterich We should have a working solution first, then improve upon it, so for now, what you've done is more than enough for the time being 👍

**Comment by charlescgs** [comment]
Interesting..
I updated OneDrive via WinUtil and then runned `remove OneDrive` tweak and despite an error it looks like it deleted it this time.
![image](https://github.com/ChrisTitusTech/winutil/assets/135472912/eb04beb1-d728-4ab4-ac8e-02f156f98dff)
OneDrive is gone from the Explorer, Apps and WinGet.

**Comment by Marterich** [comment]
> Interesting..
> I updated OneDrive via WinUtil and then runned `remove OneDrive` tweak and despite an error, looks like it deleted that app this time.
> ![image](https://github.com/ChrisTitusTech/winutil/assets/135472912/eb04beb1-d728-4ab4-ac8e-02f156f98dff)
> OneDrive is gone from the Explorer, Apps and WinGet.

Nice, from the logs it looks like you were still running the _old official winutil release_
Once my PR gets merged, even the errors in the terminal should go away, and the removal should be a bit more stable in total
