### ISSUE TITLE
Numlock on boot is not working

### ISSUE THREAD

**Issue by shomilsaini** [ChrisTitusTech/winutil#2152]
**Describe the bug**
Selected NumLock on startup option and see the error below (screenshot attached).

```
Enabling Numlock on startup
Set-ItemProperty:
Line |
1989 |          Set-ItemProperty -Path $Path -Name InitialKeyboardIndicators  …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find drive. A drive with the name 'HKU' does not exist.
```

**To Reproduce**
1. Go to 'Tweeks'
2. Click on 'NumLock on Boot'
3. See error

**Expected behavior**
NumLock should be enabled on boot

**Screenshots**
![crop_Screenshot (93)](https://github.com/ChrisTitusTech/winutil/assets/46788173/d3a963e7-757f-47ce-9eed-f0557056979a)

**Additional context**
Used to work before.

**Comment by og-mrk** [comment]
This is turned out to be a bigger issue then what it seems on the surface, will be working on it. (read [this issue](https://github.com/ChrisTitusTech/winutil/issues/2154) to follow-up on the progress)

Thanks for reporting this issue @shomilsaini 
as without reporting it, it might not be noticed for a longer time.

**Comment by Real-MullaC** [comment]
Hello @shomilsaini,

This should be fixed now. If you are still having any issues please let us know.

If this issue is fixed could this please be closed?

**Comment by shomilsaini** [comment]
Thanks everyone for your efforts. I have not tested it myself, but I am sure it is fixed if you guys have confirmed it.
