### ISSUE TITLE
File Manager - Remove left nav entries and pins

### ISSUE THREAD

**Issue by cswanson2** [ChrisTitusTech/winutil#2164]
**Is your feature request related to a problem? Please describe.**

I am very frustrated to always have the pins in file manager - Home, Gallery, Downloads, Documents, Pictures, Music, Videos
Image attached. There are hit or miss ways to remove them, but inconsistent and hard to find.

**Describe the solution you'd like**
A section to select or de-select which ones you want to see in File Manager

**Describe alternatives you've considered**
Doing this manually is hit or miss - and with Windows 11 so far it's mostly all misses, not sure how to do it.

**Additional context**
![Screenshot 2024-06-25 133702](https://github.com/ChrisTitusTech/winutil/assets/16309056/69564e16-7092-49c1-acaf-9afa2992820c)

**Comment by cswanson2** [comment]
I will be happy to help test this on multiple Windows machines, help in any way I can - I love your tool, and this would just be a really convenient "place to put this" type thing.

**Comment by MyDrift-user** [comment]
I already looked into that some time ago. As far as I got it to work you can get a list of items, but which one are pinned and which one are only there because u used them often so that they got recommended in explorer isn't determinable. In addition u can't choose the order per se, you'd have to unselect all and reselect them in the right order. 

Because of these reasons I gave up on that Idea. If someone finds a way it would be a cool feature if executed in a good way to be compact but functional it would be a cool feature, but as good as I tested some designes but with every one it would just be big and almost better to just do manually.

**Comment by Marterich** [comment]
Anyone experimenting with this please keep in mind that it is quite a delicate thing to dig into the explorer internals, so expect your PR to be denied if it does anything more but quite superficial settings/registry changes. 
Messing with the explorer internals can completely break your system quite easily

**Comment by cswanson2** [comment]
Respect @MyDrift-user and @Marterich , solid answers. If I ever have some sort of epiphany I'll let you know, else maybe it will just be an unfulfilled wish ;-)

I don't know you're specific processes here but please feel free to keep open or close this as you see fit.

Thanks
