### ISSUE TITLE
How to uninstall Winutil?

### ISSUE THREAD

**Issue by JasonMKY** [ChrisTitusTech/winutil#2189]
What's the powershell command to uninstall winutil?

**Comment by og-mrk** [comment]
@JasonMKY 
WinUtil doesn't get installed at all onto your system, as it's a PowerShell Script, not a program.

**Comment by JasonMKY** [comment]
> @JasonMKY WinUtil doesn't get installed at all onto your system, as it's a PowerShell Script, not a program. In other words.. no need to worry about "Uninstalling" WinUtil, **because it did get installed** in the first place.

Did or didn't? 
Also, what's Script.Ks.Malware.1747? I scanned in virustotal.

**Comment by og-mrk** [comment]
> > @JasonMKY WinUtil doesn't get installed at all onto your system, as it's a PowerShell Script, not a program. In other words.. no need to worry about "Uninstalling" WinUtil, **because it did get installed** in the first place.
> 
> Did or didn't?

Didn't*
My bad, I've corrected it in the original comment.

> Also, what's Script.Ks.Malware.1747? I scanned in virustotal.

I'm no expert on Cyber-security and anything related to Anti-virus & Anti-Malware detection, but from my own experience with this project and how it runs, and on top of that I've been contributing on a regular basis to this project, (started about 4 months ago, as I enjoy learning new things and use this tool in every new Windows 10/11 installation)

With that being said.. I can say with full confidence that `winutil.ps1` version `24.06.25`, _and similar situation with earlier versions of WinUtil_, being detected/flagged as a Malicious File in one sandbox out of 64 others (as of time of writing).. is nothing but a false positive, and I bet that the reason behind one sandbox that've flagged it as a Malicious File, is because in the relations tab of the scan, you'll notice the following:

1. There's an ip address which's flagged as malicious one.. it's literally own by Microsoft themselves 😂 ([link to the ip scan on VirusTotal](https://www.virustotal.com/gui/ip-address/204.79.197.203)), maybe this's due to the fact that WinUtil requests files from Microsoft's Official Links, like recently I've seen it used in Autologin configuration option, which's a Sysinternal tool developed by Mark Russinovich, Copyright @ 2002-2016 ([link to Autologin over on Microsoft Docs](https://learn.microsoft.com/en-us/sysinternals/downloads/autologon)).
2. The other one is a `.dll` file ([link to it](https://www.virustotal.com/gui/file/cb4caf485987354e0ebb4e4fb8b28c139a9a61c458ad97e8ba2c9b4b24fafd6b)), which I do agree it may sound a bit scary.. but after further investigation ([_looking through the details tab_](https://www.virustotal.com/gui/file/cb4caf485987354e0ebb4e4fb8b28c139a9a61c458ad97e8ba2c9b4b24fafd6b/details)).. it's most likely a "By Product", or a `.dll` file which's used by the GUI Framework that WinUtil uses to render it's GUI, which's called Windows Presentation Foundation (WPF), a .NET Framework that was originally developed by Microsoft, and later was Open-Sourced under the MIT License, [_source_](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/) + [Microsoft Docs on what it's in detail](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/overview/?view=netdesktop-8.0)).

**Comment by JasonMKY** [comment]
> > > @JasonMKY WinUtil doesn't get installed at all onto your system, as it's a PowerShell Script, not a program. In other words.. no need to worry about "Uninstalling" WinUtil, **because it did get installed** in the first place.
> > 
> > 
> > Did or didn't?
> 
> Didn't* My bad, I've corrected it in the original comment.
> 
> > Also, what's Script.Ks.Malware.1747? I scanned in virustotal.
> 
> I'm no expert on Cyber-security and anything related to Anti-virus & Anti-Malware detection, but from my own experience with this project and how it runs, and on top of that I've been contributing on a regular basis to this project, (started about 4 months ago, as I enjoy learning new things and use this tool in every new Windows 10/11 installation)
> 
> With that being said.. I can say with full confidence that `winutil.ps1` version `24.06.25`, _and similar situation with earlier versions of WinUtil_, being detected/flagged as a Malicious File in one sandbox out of 64 others (as of time of writing).. is nothing but a false positive, and I bet that the reason behind one sandbox that've flagged it as a Malicious File, is because in the relations tab of the scan, you'll notice the following:
> 
> 1. There's an ip address which's flagged as malicious one.. it's literally owned by Microsoft themselves 😂 ([link to the ip scan on VirusTotal](https://www.virustotal.com/gui/ip-address/204.79.197.203)), maybe because the fact that WinUtil requests files from Microsoft Official Download Links, for example I recently come across the Autologin configuration option, which's a simple configuration button which launches a Sysinternal tool (Named `Autologin`) developed by Mark Russinovich, Copyright © 2002-2016 ([link to Autologin over on Microsoft Docs](https://learn.microsoft.com/en-us/sysinternals/downloads/autologon)), and other tools and programs that points to Microsoft Official URL, and thereby there own servers which they host these files.
> 2. The other one is a `.dll` file ([link to it over on VirusTotal](https://www.virustotal.com/gui/file/cb4caf485987354e0ebb4e4fb8b28c139a9a61c458ad97e8ba2c9b4b24fafd6b)), which I do agree it may sound a bit scary.. but after further investigation ([_looking through the details tab_](https://www.virustotal.com/gui/file/cb4caf485987354e0ebb4e4fb8b28c139a9a61c458ad97e8ba2c9b4b24fafd6b/details)).. it's most likely a "By Product", or a `.dll` file which's used by the GUI Framework that WinUtil uses to render it's GUI, which's called Windows Presentation Foundation (WPF), a .NET Framework that was originally developed by Microsoft, and later was Open-Sourced under the MIT License, [_source_](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/) + [Microsoft Docs on what it's in detail](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/overview/?view=netdesktop-8.0)).

Alright, thanks for your input!

**Comment by Real-MullaC** [comment]
@JasonMKY if your issue is fixed please close this issue. If not please let us know.
