### ISSUE TITLE
Suggestion For WIn Utility

### ISSUE THREAD

**Issue by DarkSideAm** [ChrisTitusTech/winutil#2199]
My suggestion is to have a multi-iso downloader baked into the Windows tool's ability to download/update. Windows ISOs, Linux, and other iso tools

@og-mrk

**Comment by og-mrk** [comment]
@DarkSideAm I do like the suggestion.. but it'll take some time to implement & test, so for the time being, we can't say for sure that your suggestion will be added into MicroWin.

Also, I do appreciate that tagging (mentioning) me is somewhat a way of showing trust (.. or so I beileve), but if you mistaken me as an actual maintainer of the project, then I'm sorry to inform you that I'm not one, I'm simply a volunteer that enjoys contributing to the project, that's all.

So I would like you to not mention me at seemingly random places because, as I've previously stated, I'm simply a contributor to the project.. _not a maintainer_.

**Comment by DarkSideAm** [comment]
> @DarkSideAm I do like the suggestion.. but it'll take some time to implement & test, so for the time being, we can't say for sure that your suggestion will be added to MicroWin.
> 
> Also, I do appreciate that tagging (mentioning) me is somewhat a way of showing trust (.. or so I beileve), but if you mistaken me as an actual maintainer of the project, then I'm sorry to inform you that I'm not one, I'm simply a volunteer that enjoys contributing to the project, that's all.
> 
> So I would like you to not mention me at seemingly random places because, as I've previously stated, I'm simply a contributor to the project.. _not a maintainer_.

sorry I'm all new to this git hub scene who should i be tagging instead

**Comment by og-mrk** [comment]
If it's an urgent problem (lets day in the Latest Stable Release, there's a bug which crashes the tool upon specific interaction, or even worst.. makes breaking changes to your system 😨).. then you can do @ChrisTitusTech to notify him (Owner of the project/repository) about this critical issue.

Otherwise.. it's better to not tag anyone, as it might annoy them (this's my own opinion.. and I think other contributors agree on this).

Just reporting an issue or making a suggestion is already more then enough, anyone who've free time might take a look into your Issue Ticket, and probably fix the problem in a PR or provide feedback/help in the form of comments on your Issue.

**NOTE**: for me.. I didn't really get or anything when you tagged me previously, I just wanted to clarify some things, so hopefully everything is good 👍
