### ISSUE TITLE
IRM in some Windows installations is no configured

### ISSUE THREAD

**Issue by jeremiassamuelzitnik** [ChrisTitusTech/winutil#2206]
When you run _irm christitus.com/win | iex_ in some old installations it is not avilable or need to configure internet explorer.
As workarround you can change the command: _powershell "(New-Object System.Net.WebClient).DownloadString('https://christitus.com/win')|iex"_

**Comment by jeremiassamuelzitnik** [comment]
In the other hand you can use this comand in the search bar o run menu and if you press CTRL+SHIFT+ENTER you can open it directly with admin privileges

**Comment by Marterich** [comment]
According to Microsofts Dokumentation, the irm alias exists on all current windows versions.
I would actually refrain from adding yet another way of starting winutil to the readme because it's already a bit overloaded in my opinion. 
Also there are already at least two different options documented on how to start winutil
