### ISSUE TITLE
Winutil (Issues when installing)

### ISSUE THREAD

**Issue by DarkSideAm** [ChrisTitusTech/winutil#2233]
Hi All. I observed a minor issue with the Win utility while installing the selected apps from the installed programs; however, when installing, it says 1 of 24 and remains that way while the programs continue to install. It remains stuck like that during the entire process. Does anyone else have the same issues? The programs still install without problems. Sometimes VLC doesn't always install.

also can someone please explain why it's asking this about credentials it's only just recently that this is happening.

**Screenshots**
![Screenshot_1](https://github.com/ChrisTitusTech/winutil/assets/173422923/84d89b30-97af-4bb6-9f26-21df4091ee29)
![Screenshot_2](https://github.com/ChrisTitusTech/winutil/assets/173422923/dfcc1c6c-f8f9-4712-9dbf-8324a37b6c76)

@og-mrk

**Comment by og-mrk** [comment]
@DarkSideAm, thanks for reporting this issue

The progress bar not updating is probably some logic error in the code, I'll look into it.

The pop-up window is asking to use credentials to install an app for another user because some apps, like Spotify, don't like to be installed in the Admin context.. so we need a way to install these apps in a reqular user mode, and the current solution isn't perfect by any means (I believe it actually interferes with unattended config use.. could be wrong on this), but it worked at the time, but it needs some improvements.

**Comment by og-mrk** [comment]
@DarkSideAm
I'd like to inform you that I've created a PR which solved this issue, [link to it](https://github.com/ChrisTitusTech/winutil/pull/2271).
