### ISSUE TITLE
u should have this apps too 

### ISSUE THREAD

**Issue by meetkool** [ChrisTitusTech/winutil#2318]
**Is your feature request related to a problem? Please describe.**
ya idk just wanted say that WinDirStat , foldersizes , Bluestacks and whatsapp are mising in this 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MyDrift-user** [comment]
Hey @meetkool 

Whatsapp = Facebook = No, it was inside the Utility for a time but the winget package is way outdated so it got removed
WinDirStat was purged 2 weeks ago because it is also outdated, an alternative would be WizTree
BlueStack 5's installation process forcibly install BlueStacks X and a crypto wallet alongside it
