### ISSUE TITLE
Disabling Hyper-V Completely for Performance Boost in Gaming & Other Hypervisors Like VMware etc....

### ISSUE THREAD

**Issue by its-ashu-otf** [ChrisTitusTech/winutil#2329]
**Hyper V is enabled by default in Windows 11 Pro that causes slowdown for other hypervisors like VMWare etc.**
That said, you might want to disable Hyper-V as it's known to cause slowdowns and performance issues when you run other hypervisors in your system. The fact that it’s built into Windows 11 Pro, Enterprise, and Education versions also serves as a double-edged sword because removing it is a rather complex process. 

**Solution**
Here is a batch script by @its-hritika to disable hyper v completely https://github.com/its-hritika/OptimumWindows/blob/main/DisableHyper-V.bat

**Request**
Titus can u make a tweak that run these script tweaks and disables hyper-v completely?

**Comment by Marterich** [comment]
Hi @its-ashu-otf, 

Can you provide any reference to Hyper-V being enabled by default on Win 11 Pro? This would be news to me and I also cannot find any public sources stating this.
 
Also, while it _might_ technically be possible for slowdowns to appear due to having Hyper V installed and enabled, I haven't seen any real-world slowdowns in the past years working with Lots of different PCs using Hyper-V but, of course, I might not have encountered it. Some kind of measurable performance difference would be really helpful for the decision if this would be a good fit for winutil.

As it is I would refrain from including this kind of tweak.
- afaik, you have to **manually** enable the feature to use it, and as long as this not enabled the tweak would be unnecessary.
- If someone actually manually enabled it, the tweak disabling it would most likely just be annoying, also people playing around with Hyper-V seem to me like the tinkerer who shouldn't need a button to undo his work anyway. (Not the main winutil audience)

**Comment by its-ashu-otf** [comment]
Hey, 

By default windows 11 has hypervisor security enabled which is nothing but using hyper v to enforce security.

Now let me tell you how I found this.. actually i was trying to install VMware workstation pro on my fresh installation of windows and suddenly I got a pop up That multiple hyper visors are being detected without even being enabled. So when I looked it up I came across this reddit post stating the same https://www.reddit.com/r/pcmasterrace/comments/1c3qrf9/in_case_you_didnt_know_all_windows_11/ 

And let me tell u the performance difference I'm using a good laptop with ryzen 5800h paired with a rx 6600m 8GB graphics and in rdr2 with high preset with hyper v enabled by default I was getting around 100 - 120 fps and when I used this script and disabled hyper v My fps went upto 150 - 165 fps. Also VM's in VMware Feel more optimised now and I've tested this across 3 laptops and performance improvements are very much noticeable especially on low end machines with windows 11. 

I hope this would be enough

**Comment by Marterich** [comment]
Hey, 
I've discussed this a bit with some of the other contributors and here's the summary as a short list.

**1. Performance vs. Security:**
Disabling VBS (Virtualization Based Security) might increase gaming performance slightly, but it compromises security. 
**2. Impact on Users:**
Most users may not benefit significantly from disabling VBS, and therefore only degrade their security when enabling this feature (we have seen almost no performance difference in our tests) 
**3. User Awareness:** 
There is concern that users may not fully understand the security implications of such a tweak, even if warnings are provided.
**4. Tool Philosophy:**
Winutil focuses on enhancing privacy and user experience without compromising security. Including a tweak that weakens security goes against this philosophy.
### Decision: 
After considering these points, I won't add a PR in winutil for this feature. A tweak like this would rather be helpful in a Repo that focuses on Windows Gaming Performance. 

That said, the people I discussed this with and I, are also _only_ contributors. Chris is the only **maintainer** of winutil so everything I said should be interpreted as personal opinion. We cannot stop you or anyone else from creating a PR. At the end of this all, Chris is the one who decides when merging, if he wants to accept something like this.

**Comment by its-ashu-otf** [comment]
I understand your points very well no issues you're right but i was thinking like to add these to advance tweaks nothing more. But no issue I'll close this issue. Anyways Thanks ❤️
