### ISSUE TITLE
Close Button looks odd in Pre-Release 24.07.11

### ISSUE THREAD

**Issue by og-mrk** [ChrisTitusTech/winutil#2338]
### Describe the bug
The Close Button Icon looks odd, it doesn't align perfectly with Settings Icon and doesn't look the same as Stale Release 24.06.28

### To Reproduce
1. Open a PowerShell window as Admin
2. Run `irm christitus.com/windev | iex` to get & run the latest pre-release version of WinUtil
3. Wait for WinUtil GUI to show-up
4. see the Close Button Icon.

### Expected behavior
It should be the same as the stable release 24.06.28, which means that the Close Button is aligned with Settings Button.

### Screenshots
![image](https://github.com/ChrisTitusTech/winutil/assets/70659536/5e5d7543-341f-403f-8aa0-05faebb29765)

### Additional context
This'll be fixed in the next UI Refactoring PR, so I made this issue to document a visual problem found in pre-release.
Linking this issue to #2226

**Comment by MyDrift-user** [comment]
Hey @og-mrk 
I also noticed that. May it be due to the font change?
The close cross is just a character that will get affected by font changes. 
The conent of it wasn't changed since you removed the trailing whitespaces, so it is most likely that from my guessing.

![image](https://github.com/user-attachments/assets/e4da2a81-8c93-4587-ace6-81a3c3cdebd8)
