### ISSUE TITLE
Windows 11 volume mixer keep resetting the volume audio to 100%

### ISSUE THREAD

**Issue by HappyLoLTroll** [ChrisTitusTech/winutil#2379]
## Describe the bug
Windows 11 volume mixer keep resetting the app volume to 100% when setting the volume app to like 20% on the volume mixer and reopen the app.

## To Reproduce
1. Open an app and change the volume in the volume mixer to 20%
2. Close and reopen the app
3. The volume is now 100%

## Expected behavior
The volume has to be 20%, not 100%.

## Screenshots
I did a video of the problem. https://youtu.be/Muk68Ii-TaI

## Additional context
I created the ISO using MicroWin and these are my only tweaks
![immagine](https://github.com/user-attachments/assets/e4df8192-b2f0-453d-8d29-d1461734b978)

**Comment by trenton4k** [comment]
If you do not have sound anymore (because you played around with Windows mixer settings) nothing will work but:

Copy and paste the following text into an editor file (Windows Notepad for example) and save it as something.bat. Then run the file!


@ECHO OFF

ECHO Reset Volume Mixer Settings...

NET STOP Audiosrv
NET STOP AudioEndpointBuilder

REG DELETE "HKCU\Software\Microsoft\Internet Explorer\LowRegistry\Audio\PolicyConfig\PropertyStore" /F
REG ADD "HKCU\Software\Microsoft\Internet Explorer\LowRegistry\Audio\PolicyConfig\PropertyStore"

NET START Audiosrv
