### ISSUE TITLE
Add and Activate Ultimate Performance Profile does not work

### ISSUE THREAD

**Issue by ejouellette** [ChrisTitusTech/winutil#2428]
When I click on "Add and Activate Ultimate Performance Profile" button under Performance Plans,
in the PowerShell window I get the message,
"Installing Ultimate Performance plan...
> Ultimate Performance plan installed.
WARNING: You cannot call a method on a null-valued expression."

Then I check in Windows Control Panel->Hardware and Sound->Power Options,
and it only has Balanced plan.

If I click on "Remove Ultimate Performance Profile" button in CTT, I get the message,
"Ultimate Performance plan is not installed."

Please help!

**Comment by Marterich** [comment]
Hi @ejouellette, 
Could you please run the following commands and post the output
WARNING: This will reset any modifications you might have done to the Power Profiles.
```
PowerCFG -RestoreDefaultSchemes
```

```
powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61; powercfg -list
```

If no Profile called "Ultimate Performance" is displayed, it simply doesn't seem to be supported on your device.
In that case, we should fix the error handling on the side of winutil so that a proper Warning is displayed to the user instead of the "null-value" error.

**Comment by ejouellette** [comment]
After posting, I found this article:
https://www.dell.com/community/en/conversations/inspiron/g5-5590-high-performance-missing/647f97b0f4ccf8a8deab95e5

I followed the instructions, and that worked!
I think the first command: reg add HKLM\System\CurrentControlSet\Control\Power /v PlatformAoAcOverride /t REG_DWORD /d 0
allowed me to enter the new profiles, including the Ultimate Performance profile.

**Comment by ejouellette** [comment]
I also tried the commands you listed, and they now work as well.
Thanks!
