### ISSUE TITLE
Tixati download link does not install anything

### ISSUE THREAD

**Issue by tibrusjer** [ChrisTitusTech/winutil#2430]
## Describe the bug

When initiating the installer from Tixati the PowerShell begins the process and claims it succesfully installed said program, but when searching all over my drive for the program nothing show up (even when manually searching in the file explorer).

The manual installer from their website does still work.

## To Reproduce

1. start utility
2. choose tixati checkmark
3. click "install/upgrade"
4. watch powershell claiming a job well done
5. try and start the alleged installed software you still don't have installed.
6. 

## Expected behavior

That said installer actually installs said software and being able to use the software after said install process.

## Additional context
This is a highly LOW PRIORITY issue, mostly wondered if it is an utility issue or winget issue.

**Comment by og-mrk** [comment]
Hello @tibrusjer 
Thanks for reporting this, and the reason behind not finding the installed program after installing it, in both WinGet (the package manager) and WinUtil.. because it's **the portable edition of Tixati**,  meaning it's downloaded in `%LOCALAPPDATA%\Microsoft\WinGet\Packages` folder (either this foldor or somewhere else, can't remember exactly where it installs portable apps), in other words, you won't find Tixati by searching it up.

So this is a WinGet thing, not WinUtil. When I added Tixati package to winget-pkgs repo, I chose the Portable Edition of it, not installer (because the installer would not Silently install. Therefore, it failed WinGet testing pipeline)

You can run it Tixati by typing `tixati_Windows64bit` or `tixati_Windows32bit` in your terminal (depending on your hardware.. but it'll most likely be 64 bit).

I hope this answers your question. If you have anything else you're wondering about (and it's related to this issue ticket), you post it and I'll reply as soon as I can.
