### ISSUE TITLE
Discord Installation on Windows 11 is not installed correctly

### ISSUE THREAD

**Issue by hambrosia** [ChrisTitusTech/winutil#2443]
## Describe the bug
Discord installation appears to not integrate with Windows Desktop Environment when installed via winutil on Windows 11

Windows Version: Professional Version 10.0.22631 Build 22631

## To Reproduce
1. Install Discord via winutil on a fresh Windows11 host
2. Open and log into Discord
3. Pin Discord and move it to the left on the taskbar
4. Restart Computer
5. On restart, Discord is no longer pinned

## Expected behavior
Discord should remain pinned.

**Comment by MyDrift-user** [comment]
Hello @hambrosia 

This issue is not because of winutil, nor should be the issue of winget.
I am on the same build as you and tested it out, but it stayed pinned as expected.

- I found [this](https://www.reddit.com/r/WindowsHelp/comments/143k5vy/shortcuts_on_taskbar_not_staying_pinned/) reddit post with a user that has the same issue but with firefox.
- Another way of fixing it was tried over [here](https://answers.microsoft.com/en-us/windows/forum/all/icons-will-not-stay-pinned-to-taskbar/143e801f-0d95-433c-8087-874c6f3e7c60?), but it looks like that did not work.

I suggest running discord with admin, while running right click on the taskbaritem and pin it from there, since I could not recreate the issue and neither of the links seem to be marked as fixed I can't promise that something will work.

**Comment by hambrosia** [comment]
@MyDrift-user thanks for trying to repro. 

It's not a company-provided device. 

I also noticed issues when trying to uninstall Discord via the winutil and afterward via "add or remove programs." 

It would remove the icon when uninstalling but a blank icon would remain and the settings and login data were not removed. 

Possibly just something went wrong with my particular install, it may not be the winutil but I wanted to raise it in case there is something happening here. I'm fine to close this if we can't reproduce on other machines though.

I installed quite a few other applications at the same time via winutil so I wonder if there was some interaction or contention for the same resources at some point.

**Comment by ruxunderscore** [comment]
> I also noticed issues when trying to uninstall Discord via the winutil and afterward via "add or remove programs."
> 
> It would remove the icon when uninstalling but a blank icon would remain and the settings and login data were not removed.

I have actually noticed this issue with Windows in general. Some applications leave behind shortcuts sometimes, and Windows just leaves broken links constantly. 

>I installed quite a few other applications at the same time via winutil so I wonder if there was some interaction or contention for the same resources at some point.

This is unlikely, as the downloads aren't threaded and happen one after the other. (This is mostly a Windows limitation, in general. MSIX packages can have 6 installations at once, while EXE and MSI packages are limited to 1 installation at a time, even if we were to try to find a way to do parallel downloads.)

**Comment by stuckydev** [comment]
This is a known problem for Discord, (maybe please rename title?). It would be very great if Chris or a Maintainer could create a fix for this. The cause is, that Discord creates a new folder/path on each update → so Windows keeps forgetting the Taskbar-Settings for Discord on each Discord-Upate. Would be very great if one could program a scheduler task which sets the tray settings on each reboot (discord has lots of updates). I did try it with PowerShell/ChatGPT but it couldn't find the right Registry keys.

**Comment by hambrosia** [comment]
I never noticed this issue until using the winutil to install Discord. Could it be winutil is using a version of the Discord application that is susceptible to this problem?
