### ISSUE TITLE
Please add this program

### ISSUE THREAD

**Issue by MrMyth** [ChrisTitusTech/winutil#2446]
Please add this program:

XnView MP: https://www.xnview.com/en/xnviewmp/
unchecky: https://unchecky.com/
Universal Viewer http://www.uvviewsoft.com/ -or any GOOD program for PDF: Adobe PDF format, plus DJVU XPS CBR CBZ.
QuickTime codecs.

**Comment by YusufKhalifadev** [comment]
Ok I will add them in a pull request

**Comment by YusufKhalifadev** [comment]
@MrMyth XnView MP: May be discarded by chris because it's not opensource and it's a license free ware so maybe it will not be added

**Comment by YusufKhalifadev** [comment]
@MrMyth  I will add unchecky only because the other software is kinda obselete

**Comment by YusufKhalifadev** [comment]
@MrMyth Added the app in #2447

**Comment by MrMyth** [comment]
> @MrMyth I will add unchecky only because the other software is kinda obselete

All this programs is free. Can you add IrfanView?
DJVU XPS CBR CBZ any soft for this files?

**Comment by SHR1SHAK** [comment]
Unchecky has been update since v1.2 (April 8, 2018). https://unchecky.com/changelog
I don't think it's a good idea to add applications that are not currently being maintained.

**Comment by ruxunderscore** [comment]
Universal Viewer is freeware, BUT it's not Open Source and the free version was last updated in 2012. For a more up-to-date version you have to go with the Trialware, then paid Pro version, which hasn't been updated since 2021. Also, the free version doesn't have an installer, it's zip file only. 

Chris doesn't like adding software like this, and it would be more difficult to implement than if it had a supported installer through winget. 

Just to clarify, we tend to stick to FOSS software, with emphasis on the F. The only exceptions to the OS rule has been frequently used software.

**Comment by stuckydev** [comment]
> Just to clarify, we tend to stick to FOSS software, with emphasis on the F. The only exceptions to the OS rule has been frequently used software.

Then I am voting here for **IrfanView** - it is freeware
URL: [www.irfanview.com](url)
Latest Release is from: April 2024
(Source: https://irfanview-forum.de/forum/program/news)
