### ISSUE TITLE
Always reinstalling Winget and User prompt issue

### ISSUE THREAD

**Issue by Sozachiago** [ChrisTitusTech/winutil#2458]
I'm encountering an issue where every time I use Winutil, it reinstalls winget, even if I keep it open and just install another program. Despite being on version 1.8.1911, it keeps indicating that winget is outdated.
![F4O2YXz](https://github.com/user-attachments/assets/648dfd69-449c-4ef2-8727-78979ccf454b)

also the most annoying thing is that for every program that I try to install it asks for a User credential prompt even tho I'm opening it as admin, how do I get rid of this user credential prompt?

**Comment by MyDrift-user** [comment]
Hey @Sozachiago 

The user promt is not because it needs to run as admin, quite the other way around.
Some applications do not like being installed as admin, which is why this is a "fallback" installs the respective application not in an admin promt. hope this clears up the confustion.

Still the main issue here is not addressed. The Winget Update does not seem to work correctly and that might also be the reason why the installs do not work as expected and want to try it using a non admin shell.

Just from looking at the image it looks like it does not know what the latest winutil release is, you have v1.2.10691 and "latest one" is v1.8.1911.

**Comment by Sozachiago** [comment]
> Hey @Sozachiago
> 
> The user promt is not because it needs to run as admin, quite the other way around. Some applications do not like being installed as admin, which is why this is a "fallback" installs the respective application not in an admin promt. hope this clears up the confustion.
> 
> Still the main issue here is not addressed. The Winget Update does not seem to work correctly and that might also be the reason why the installs do not work as expected and want to try it using a non admin shell.
> 
> Just from looking at the image it looks like it does not know what the latest winutil release is, you have v1.2.10691 and "latest one" is v1.8.1911.

Turns out it was the Winget version causing the issue, like you said. It was showing 1.2.10691, but I thought WinUtil had updated it since it kept trying every time I opened it. I manually updated it to 1.8.1911, and now it's working. Thanks a lot for the help <3 and sorry for taking up your time
