### ISSUE TITLE
Custom install dir for all selected apps?

### ISSUE THREAD

**Issue by jult** [ChrisTitusTech/winutil#2503]
Honestly, I have never liked the way Windows structured this on my storage. I found the folder names too long and ugly. Usually, when I install something manually, I select my own dir for it. Would be great if I could set that once for all apps I would select in this tool too..

**Comment by Marterich** [comment]
Could technically be added using the argument
> -l, --location	
Location to install to (if supported).

The problem is, that it relies heavily on the Dev's of the Applications to support the winget location argument so that it will definitely not work across the board. 
Keeping this in mind, I'm not sure if it's worth the dev time to implement and maintain the feature and the increased UI clutter for a feature which will work _sometimes_ and result in issues like "my app didn't install In the specified location" were the winutil Dev's are helpless because it's the fault of the application

**Comment by jult** [comment]
Ah yes, of course. The thing is though, thus far all the apps I've been using on Windows are either portables or allowed me to choose a custom dir during install. So what this essentially means is that I will not be using this tool to install apps with. Not a biggy, just less convenient. Also a personal thing where I never like the defaults programs use or pick, and this winutil does just that, use all defaults. Which, i.m.o. is the opposite of what the tweaks intend to do, but hey, could be me.

**Comment by Marterich** [comment]
I just glanced at the winget package manifests and if I'm correct of more than 50k packaged installers, only around 2k support the custom install path... Also, I found discussions/issues on https://github.com/microsoft/winget-cli dating back multiple years regarding the behavior for custom install locations. 
Until winget provides an easy way like a return code for notifying the user that a custom location is not supported, I don't see a maintainable solution that could be implemented in winutil.

Considerations for the future could be: 
- Graphically show the user which installers support a custom path and which doesn't
- Switch away from winget to a package manager that supports paths by default
