### ISSUE TITLE
Windows Subsystem for Linux: Should it be under the Feature or the Install tab of Winutil?

### ISSUE THREAD

**Issue by billytwotone** [ChrisTitusTech/winutil#2650]
A few days ago I looked for Windows Subsystem for Linux on Winutil, because I wanted to install it. I searched the install section of Winutil, and it was not there.  I eventually installed it with the standard Windows terminal by copying the command provided by the developers, and it worked ok.

I looked at the latest Winutil today, and to my surprise, I stumbled upon Widows Subsystem for Linux in the "Config" section of Winutil. Previously, I had only looked for it in the "Install" section of Winutil. 

To me, I think that it would be more intuitive if Windows Subsystem for Linux was listed in the Install section of Winutil especially as there is a section for Microsoft tools, which should probably be renamed Microsoft stuff. Any comments?

**Comment by ruxunderscore** [comment]
I see no one has commented. I believe it should stay where it is. WSL is an Optional Feature in Windows, and is the proper way to enable WSL.

**Comment by billytwotone** [comment]
All of the 300 apps (approx) are optional, so why not include the option of WSL there too?

**Comment by 4yman-0** [comment]
WSL is enabled from Windows Features in Control Panel *(or Powershell/cmd/DISM/etc)*. I think it should be in "Features".

**Comment by MyDrift-user** [comment]
WSL is as others stated a Windows Feature, meaning appropriate in the place where the other Windows Features are.
In addition to that, there are no Windows Features listed under "Microsoft tools" that are Windows Features to my knowledge.

So I do agree with the other ones. We differenciate between Windows Features and Applications, even if a Windows Feature might include or just straigt up is an application.

Since this issue is already opened for some time and commentors outside from op are agreeing that WSL is appropriate under Features, I am going to close this Issue now.

Thanks for reporting and if u have any questions, just ask :)

/close
