### ISSUE TITLE
OBS Studio installed automatically with .json import

### ISSUE THREAD

**Issue by Peppernrino** [ChrisTitusTech/winutil#2819]
Whenever I choose to import a .json file, OBS Studio ends up getting ticked and I keep installing it by accident.

1. Create .json export excluding OBS Studio
2. Close Powershell and reopen winutil
3. Import *.json
4. Check fo see that OBS Studio is being ticked

**Comment by momcilovicluka** [comment]
I conducted a preliminary test and can confirm the presence of the issue. More specifically, during the import process, if Obsidian is imported from JSON, it appears to select both 'Obsidian' and 'OBS' simultaneously. Based on this observation, the root cause seems to reside within the matching logic of import functionality. I will investigate further and make a pull request.

Additionally, when reporting issues of this nature, it would be highly beneficial if you could include the JSON file that was created and used for the import attempt. This would assist in diagnosing the problem more efficiently.

**Comment by momcilovicluka** [comment]
Forgot to sync my main to upstream🙃. Seems to be working fine on the latest main when compiled from source. The latest hosted version of the tool is not yet compiled from latest main (when getting with windev or otherwise). I suggest closing this as it  seems to already be fixed in code, but not hosted as a release yet.

**Comment by Peppernrino** [comment]
I can confirm I was installing Obsidian using the tool. :)
I appreciate you looking into this. Glad it's fixed in future releases.
