### ISSUE TITLE
After install Powershell Profile -> Loading takes for ever!

### ISSUE THREAD

**Issue by herbertnikolajewskidci** [ChrisTitusTech/winutil#2825]
# After installation of the powershell profile, the loading takes almost always over 6 seconds. Is that normal? If yes could it be possible to ad a button to uninstall the profile?

## Screenshots
![image](https://github.com/user-attachments/assets/252c4cb2-da3d-4761-bc61-da80ffb8ee27)

**Comment by MyDrift-user** [comment]
Hello @herbertnikolajewskidci, thanks for reporting this :)

It took 1 second to wait for a response from github in this scenario. Usually that is because there is no/bad network connection.
The Profile seems to have some potential for improvements.

In the meantime, if you want to remove the profile you can:
- open File Explorer
- go to the nav bar
- search for `%userprofile%\Documents\PowerShell`
- There you should be able to find a file named `Microsoft.PowerShell_profile.ps1`, which you can delete.
- If you now restart Powershell, the Profile should be removed

**Comment by zmileski** [comment]
off topic but there is issue with latest version of chris titus powershell profile with loading icons

latest version
![2](https://github.com/user-attachments/assets/0401a955-92b4-42d4-bc4d-98bcfaaaf79c)


older version
![1](https://github.com/user-attachments/assets/725c0312-2fb9-4df4-acd9-db792a5f1892)
