### ISSUE TITLE
DISM Feature Toggler (WinUtil)

### ISSUE THREAD

**Issue by v6stXN46WdLBtp** [ChrisTitusTech/winutil#3033]
**Is your feature request related to a problem? Please describe.**
Currently Microwin is fairly opinionated when it comes to enabled and disabling certain DISM windows features. (https://github.com/ChrisTitusTech/winutil/issues/2602). Users that have a pre-existing install of Windows may want to customize the features available.

**Describe the solution you'd like**
A solution would be a series of checkboxes allowing the toggle of DISM features instead of using third party programs. The features checkboxes would probably be behind some kind of advanced features tab to avoid a blind configuration that renders the computer useless or vulnerable.

**Describe alternatives you've considered**
I have considered using a program called NTLite. But this is a non-OSS 3rd party program compared to an open-source all in one tool like Winutil.

**Additional context**
None.

**Comment by CodingWonders** [comment]
Most users will simply leave the default options. We want to make it so that images just work.

There are free and open-source alternatives to NTLite you can try out. I've even made [one](https://github.com/CodingWonders/DISMTools). However, don't toggle the features you want without understanding what they do. Your experience will vary after modifying the state of features or doing any other things with your Windows image.

This issue can be safely closed. /close
