### ISSUE TITLE
Chrome installed through utility has weird issues

### ISSUE THREAD

**Issue by Hellohi3654** [ChrisTitusTech/winutil#3048]
## Describe the bug

When installing chrome through the utility via winget the loading circles on tabs are laggy and UI randomly freezes and only way to fix it is to click out and back into chrome.
Installing chrome from installer downloaded from Google's official website does not have any of these issues.

## To Reproduce
1. Install chrome through utility 
2. Observe laggy loading circle and random UI freezes
3. Uninstall and reinstall chrome from Google's website
4. Issues disappear 

## Additional context

Might be a issue specific to AMD GPU's. I have a RX 6800 and have confirmed it is an issue with driver versions 24.9.1 and 24.10.1.

**Comment by MyDrift-user** [comment]
Hello there @Hellohi3654 

We use [winget ](https://github.com/microsoft/winget-cli)or [chocolatey ](https://chocolatey.org/)for installing the applications, in addition to that Google is responsable for the installers they offer, so that issue is kind off out of scope sorry.

But I would suggest trying out the command `winget install google.chrome.exe` which uses the exe installer to install chrome instead of the msi one and may help you out for this issue.

/close
