### ISSUE TITLE
Cant do a lot of things after tweaks

### ISSUE THREAD

**Issue by DatBoiiiiBryan** [ChrisTitusTech/winutil#397]
I cant restore my pc, take screenshots, search and i cant open my settings anymore either.
When i try to restore my settings/system it gives the error: VSS Encountered Problems while sending events to writers. (0x80042315
I would love to know wether i need to reset my pc to have normal access to it again.

**Comment by TOGLK** [comment]
So,

Just looking at and reading your "Issue" it sounds like you ran the script on a live system you require use of without first assessing the possible risks involved with running this application and it's various automated scripts.

My personal suggestion to you would be to simply rollback to a system state where your system was functioning (if you have backups enabled and actively being kept up-to-date).
**OR** If you did not have backups enabled, or, your backups were not up-to-date then I suggest that you move what files you can to a secondary drive and then do a reinstall of your exact Windows OS (Windows 11 or Windows 10 depending on which OS you are running).

**NOTE FOR FUTURE REFERENCE**
In the future I suggest that you research the risks involved with blindly running scripts on your system without first being prepared with a system-state backup and being well aware of the fact that this utility is not a commercial tool and so relies on the community to ensure that it is bug-free.

Unfortunately because of the tools limited user base only so many people will donate time to this project to help keep it working fluidly, if you want to see the project improve then offer up what free time you have to help improve it for everyone that uses it, after all it is a community effort with Chris as the driving force at the front!

**Comment by lincolntan36** [comment]
try running the system corruption scan in the config tab

**Comment by lincolntan36** [comment]
or you could

1.    Click on Start, type Services in Start Search. When the Services page is open, check for Volume Shadow Copy service.

2.    Right click on Volume Shadow Copy service (VSS) and Check if it is started.

3.    If it is stopped select Start or Restart.

**Comment by ChrisTitusTech** [comment]
VSS by default is set to manual and isn't changed. Simply running the tool should fix this as I updated it in march to set these to defaults.
