### ISSUE TITLE
System becomes unusable for some time after applying the tweaks, then goes back to normal

### ISSUE THREAD

**Issue by ZachKhries** [ChrisTitusTech/winutil#414]
First of all, i'm sorry as this will probably have a lot of typos... English isn't my main language.

**Describe the bug**
 This issue occurs afters applying the tweaks from your app. The system does not let me open anything related to the windows 10 UI for quite some time but then, after some minutes, it does come back to normal. Start menu does not respond correctly and anything related to the Modern UI that windows 10 have, behaves the same way. Still, everything else works just fine, like browsers, the 'This PC' icon, file explorer and even games. 

 I've tested this with windows 10 21H1, 21H2, 22H1 and 22H2. All theses isos where modified using a app called winreducer just for the sake of desabling stuff as Windows Defender, removing most of the metro apps(skype, climate, etc), disk quota, bandwidth limit.

 When the UI finally starts to behave normaly, the system works as intended so i'm just reporting this as it might be useful.

**To Reproduce**
1. Use the recommended tweaks, be it the desktop ones or the laptop
2. Restart the PC and the UI elements tied to win 10 stops working
3. Wait for a while, which sometimes took me almost 20 minutes!
4. Windows 10 UI comes back to life and system finally behaves normally

**Expected behavior**
No issues with the UI, or with any of the apps tied to windows 10

**Additional context**
Just to clarify, the system works as intended after this 'freeze' that occurs only on the windows 10 ui. After that there's absolutely no issue or what-so-ever.

 This issue was tested both on a VM and on my laptop, both just after formating the system and with just the drivers installed.

 Hope this report helps in some way. Keep it up with this awesome tool, Chris!

**Comment by TOGLK** [comment]
Hey @ZachKhries,

Do you have a list of the EXACT modifications that you made using "WinReducer" to the OFFICIAL ISO hosted on Microsoft's website?

I ask this as I am happy to try out these same modifications myself using a fresh ISO too see if maybe the issue is related to some kind of hardware bug or bottleneck that may not be apparent at first, **OR**, if it might be linked to your "WinReducer" OS modifications.

In the past while applying tweaks via the utility my system has slowed down significantly, but once applied everything went back to normal.

To me this kind of behavior is to be expected due to how vast & varied the changes that are made can be to the whole system, and so I want to help provide an additional point of data to see if we can narrow down the issue to something that MIGHT be resolvable.

**Comment by ZachKhries** [comment]
Sure thing! The only modifications that I made using WinReducer on an official ISO downloaded directly from microsoft, were:

- Remove Windows Defender
- Disable Disk Quota
- Disable Bandwidth limit
- Removed most of the Metro APPs, except cortana and windows store

 I've also made sure to protect Sysprep, virtualbox, windows search, as well as marked options to optimize the ISO without touching in any experimental functions. No services, besides anything related to windows defender, were touched in the process!

 I hope this can be of some help and, once again, thanks a lot! Your Util is simply amazing and while I had this little issue, my computer is working flawless right now.
