### ISSUE TITLE
When trying to use the Utility to install anything I get a window that throws up some microsoft credentials and nothing gets installed.

### ISSUE THREAD

**Issue by JRS222** [ChrisTitusTech/winutil#442]
After running the scripts to install the programs I get a pop-up that says 

Update ms-resource:appDisplayName? (I believe this is supposed to be "App Installer")
then tells me the microsoft version and what it does. 

Then after I click "update" the window closes and nothing happens. Rinse and repeat. 

Thanks!

**Comment by DeveloperDurp** [comment]
are you running this as an administrator?

**Comment by JRS222** [comment]
I am running poweshell as Admin, yes. I bought the executable to try and rectify but the same issue occurs.

**Comment by DeveloperDurp** [comment]
is it possible to grab a screen shot of the message you are seeing?

**Comment by JRS222** [comment]
Sorry for responding so late. I didn't expect the help to be so active. Actually I cannot. I will copy and paste the error though. One sec.

**Comment by JRS222** [comment]
1. Run CTT Windows utility as admin
2. pick program
3. Select install
4. Pop-up appears

Update ms-resource:appDisplayName? (but the icon for that window in the task bar is the app installer icon)
Trusted microsoft store app
Publisher: Microsoft Corporation
Version 1.18.2091.0

Capabilities
[long list]                                                                                    [UPDATE]

5. Click the update button.
6. Window disappears
7. Nothing was installed

**Comment by JRS222** [comment]
I just ran "dism /online /cleanup-image /restorehealth
sfc /scannow" to validate files and when I tried the util again it still came up with the same stuff.

**Comment by DeveloperDurp** [comment]
Can you try installing something through winget manually? IE running `winget install brave.brave `

**Comment by JRS222** [comment]
let me try that. I really wish other OS's supported games and software the way MS does.

**Comment by JRS222** [comment]
No winget and when I try to install the winget package from GitHub I get this screen, which is the same as before. This was on a website and the version is different. 
![Untitled](https://user-images.githubusercontent.com/79031558/204166471-84d0d9fb-94cf-4127-b853-ac0fcf44517c.png)

I press the update button and nothing happens still.

**Comment by JRS222** [comment]
I redid the irm instructions from the website and still no go

**Comment by DeveloperDurp** [comment]
Ah, that's Winget itself having an issue. You can try installing it manually through the Microsoft store

**Comment by JRS222** [comment]
I don’t have the Microsoft store  because I created the NTLite image from
the video lol

**Comment by lincolntan36** [comment]
try downloading the appx file and installing it from here 
https://github.com/microsoft/winget-cli/releases

**Comment by DeveloperDurp** [comment]
Ah, I do not have an NTLite image so I am unable to replicate the issue. That's more @ChrisTitusTech's area

**Comment by Carterpersall** [comment]
You might need winget's VCLibs dependency, you can download it at https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx

**Comment by ChrisTitusTech** [comment]
we are going to be moving away from winget soon, too many issues and Microsoft just keeps making it worse and worse. 

this should force install it on a minimal install though:
```
irm https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winget.ps1 | iex
```

**Comment by JRS222** [comment]
Turns out it was the execution policy then I could run the provided script. Big thanks!

**Comment by bksnow2** [comment]
JRS222,

Can you show what you did to get it to work?

**Comment by bksnow2** [comment]
> Turns out it was the execution policy then I could run the provided script. Big thanks!

JRS222,

Can you show what you did to get it to work?

**Comment by JRS222** [comment]
Yeah, sure when I get  on my computer

**Comment by bksnow2** [comment]
JTS222,
Thank you!!

**Comment by bksnow2** [comment]
PS C:\Users\Administrator> Get-ExecutionPolicy
AllSigned
PS C:\Users\Administrator> Set-ExecutionPolicy Unrestricted

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by
a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective
execution policy of AllSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more
information please see "Get-Help Set-ExecutionPolicy".
At line:1 char:1
+ Set-ExecutionPolicy Unrestricted
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
    + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
PS C:\Users\Administrator> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       AllSigned
 LocalMachine    Unrestricted

**Comment by bksnow2** [comment]
[Update ms-resource:appDisplayName?] pop up went away but still no Apps will install using iwr -useb https://christitus.com/win | iex

**Comment by Carterpersall** [comment]
Try `Set-ExecutionPolicy "Unrestricted" -Scope "CurrentUser" -Force`

**Comment by bksnow2** [comment]
I am getting this when I try install any app from CTT win Utility, 

Winget not found, installing it now.
Start-Process : This command cannot be run due to the error: Package failed updates, dependency or conflict validation.
At line:235 char:17
+ ...             Start-Process "ms-appinstaller:?source=https://aka.ms/get ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Get-Process : Cannot find a process with the name "AppInstaller". Verify the process name and call the cmdlet again.
At line:236 char:25
+                 $nid = (Get-Process AppInstaller).Id
+                         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AppInstaller:String) [Get-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.GetProcessCommand

Wait-Process : Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide an argument that is
not null or empty, and then try the command again.
At line:237 char:34
+                 Wait-Process -Id $nid
+                                  ~~~~
    + CategoryInfo          : InvalidData: (:) [Wait-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WaitProcessCommand

Winget Installed
7zip.7zip
