### ISSUE TITLE
malware?

### ISSUE THREAD

**Issue by GHOSTS15** [ChrisTitusTech/winutil#551]
https://analyze.intezer.com/analyses/852f2a56-a726-4b41-8be6-71902e3548f4

I scanned the file "winutil.ps1"

**Comment by joser93** [comment]
It's curious to see that sandbox in action, but, checking on the analysis that it did, marks the MainWindow.xaml download from github as malware and also  detects the command `choco feature enable -n allowGlobalConfirmation` as a possible malware. Definitely a false positive and it's open source, so anyone can check that there's no malware involved and even the terms of use of github does not allow malware to be involved into anything https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#5-site-access-and-safety.

Things can be done to mitigate some warnings, but either way, some of this sandbox tools need some improvement, so for example if detects a download and can read the code, instead of mark it as dangerous just because of that, just check what exactly code did download and check what it does.

Take for example this website: https://tria.ge/230102-3mwy2age47/behavioral1 I did the test twice and detects the minimal tweaks as ransom, just because is allowing to have the F8 boot options menu. But the other things that intezer says, isn't flaged here. So, I am more confortable using this sandbox and allows me to test more into the GUI, despite that checks stuff as malicious, still a false positive, maybe because some other software uses this to do other things but still requires a more in depth analysis and context.

**Comment by GHOSTS15** [comment]
> It's curious to see that sandbox in action, but, checking on the analysis that it did, marks the MainWindow.xaml download from github as malware and also detects the command `choco feature enable -n allowGlobalConfirmation` as a possible malware. Definitely a false positive and it's open source, so anyone can check that there's no malware involved and even the terms of use of github does not allow malware to be involved into anything https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#5-site-access-and-safety.
> 
> Things can be done to mitigate some warnings, but either way, some of this sandbox tools need some improvement, so for example if detects a download and can read the code, instead of mark it as dangerous just because of that, just check what exactly code did download and check what it does.
> 
> Take for example this website: https://tria.ge/230102-3mwy2age47/behavioral1 I did the test twice and detects the minimal tweaks as ransom, just because is allowing to have the F8 boot options menu. But the other things that intezer says, isn't flaged here. So, I am more confortable using this sandbox and allows me to test more into the GUI, despite that checks stuff as malicious, still a false positive, maybe because some other software uses this to do other things but still requires a more in depth analysis and context.

I contacted support , let's see what they reply

**Comment by ChrisTitusTech** [comment]
Yeah the thing that should trigger antivirus warnings is the removal of edge as that is system modification. I'm about to add a full removal of windows defender and smartscreen which will trigger every AV. Not much I can do at this point, I've tried to play nice in the past, but at this point I'm just going to add features folks request and say disable the antiviruses. 

On a side note: It flagging the XAML file makes no sense as that is just XML for drawing the GUI. I'd say the tool is pretty much worthless. It should flag around the edge removal or disabling UAC options as that is considered malicious because of the system modification. Just my 2 cents.

**Comment by GHOSTS15** [comment]
they replied to me ,in a nutshell they added a category to identify your files
