### ISSUE TITLE
Hi, trying to edit

### ISSUE THREAD

**Issue by Eddows** [ChrisTitusTech/winutil#647]
Hi, I was trying to edit just the Installer part 'cause i would like to use one tool to install a lot of softwares that I need to install to every fresh pc. 
So I tried to edit the script and add programs that I need. to my github for testing.
The problem is that at the start it works very well, but after few hours when I re-launch the script I get some errors.

So my question is, can I edit the file?

**Comment by DeveloperDurp** [comment]
We recently reorganized the structure of the main script so you should have no problems making modifications and launching your modified script locally. 

If your goal is to install a bunch of programs on a fresh PC you could create a simple script and use this function. From here you would only need to feed it a list of programs IE `Install-WinUtilProgramWinget "Adobe.Acrobat.Reader.64-bit,Famatech.AdvancedIPScanner,AnyDeskSoftwareGmbH.AnyDesk"`
https://github.com/ChrisTitusTech/winutil/blob/main/functions/private/Install-WinUtilProgramWinget.ps1

Otherwise you will need to modify the InputXML variable to change the checkboxes to your applications as well as modify the $sync.configs.applications variable to include your applications. Also note the name of your checkbox MUST match in both the config and applications variable and the applications must include WPF infront. 

Your best bet is to pull the entire repository and modify xaml/inputXML.xaml with your modifications. From there you can use the helper script inside the config folder to add your applications. Once ready the compile.ps1 script will build you a new winutil.ps1

**Comment by Eddows** [comment]
Thank you! I just edited adding some softwares and tried it all day.
I edited just changing names and ids of softwares, not adding them, like that:
`<Label Content="Eddow" FontSize="16" Margin="5,0"/>
                                <CheckBox Name="Installpowerbi" Content="Power BI" Margin="5,0"/>
                                <CheckBox Name="Installpdf24creator" Content="PDF24 Creator" Margin="5,0"/>
                                <CheckBox Name="Installfilezilla" Content="FileZilla" Margin="5,0"/>
                                <CheckBox Name="Installdisplaylink" Content="Display Link" Margin="5,0"/>
                                <CheckBox Name="Installeset" Content="Eset EndpointAntivirus" Margin="5,0"/>
				<CheckBox Name="Installscp" Content="WinSCP" Margin="5,0"/>
				<CheckBox Name="Installsevenzip" Content="7-Zip" Margin="5,0"/>
			        <CheckBox Name="Installnotepadplus" Content="Notepad++" Margin="5,0"/>
			        <CheckBox Name="Installdbeaver" Content="DBeaver CE" Margin="5,0"/>
				<CheckBox Name="Installadobe" Content="Adobe Reader DC" Margin="5,0"/>
				<CheckBox Name="Installoffice" Content="Office" Margin="5,0"/>
				<CheckBox Name="Installteams" Content="Teams" Margin="5,0"/>
				<CheckBox Name="Installfirefox" Content="Firefox" Margin="5,0"/>
				<CheckBox Name="Installchrome" Content="Chrome" Margin="5,0"/>
				<CheckBox Name="Installclickshare" Content="ClickShare" Margin="5,0"/>`

And for the winget ids I edited this for example:
` "WPFInstalldbeaver": {
    "winget": "9PNKDR50694P",
    "choco": "dbeaver" 
  "WPFInstalldisplaylink": {
    "winget": "DisplayLink.GraphicsDriver",
    "choco": "displaylink"
  }, 
  "WPFInstallpowerbi": {
    "winget": "Microsoft.PowerBI",
    "choco": "powerbi"
  },` 

And so on...
I don't know if I did it the right way 'cause i'm not really a developer, i've never been into programming...
But It works and it's very useful!
