### ISSUE TITLE
Install Winget in Windows Sandbox

### ISSUE THREAD

**Issue by Neowam** [ChrisTitusTech/winutil#668]
Could you add this code to install Winget into Windows Sandbox?

$ProgressPreference='Silent'
Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.3.2691/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

I got it from the https://learn.microsoft.com/en-us/windows/package-manager/winget/ site.

Maybe you can use this code as well for installing it in an alternative way when you get the error WinGet Could not be installed.

**Comment by ChrisTitusTech** [comment]
Working on a new installation using #347 
The problem with the method you gave is the version specific where it won't work in some old version of Windows and needs to be changed on each update.

**Comment by chrisjlocke** [comment]
Are there newer instructions on how to install Winget in Sandbox?  The util app tries, but fails.

<pre>
---Chris Titus Tech---
--Windows Toolbox--
Queueing Mozilla.Firefox for Winget
WARNING: Winget was not found due to un-availablity reasons
===========================================
---      Winget is not installed        ---
===========================================

Winget is not Installed. Continuing with install.
Attempting to install/update Winget
Attempting to repair WinGet using Repair-WinGetPackageManager...
----
Error: The term 'Repair-WinGetPackageManager' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
----

</pre>
Choco installs just fine.  


The Winget reinstall on the config page doesn't work .. or at least throws up a lot of errors.

<pre>
===========================================
---      Chocolatey is installed        ---
===========================================
Version: v2.5.0
Chocolatey v2.5.0
Installing the following packages:
winget
By installing, you accept licenses for the packages.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading microsoft-ui-xaml-2-7 2.7.3... 100%

microsoft-ui-xaml-2-7 v2.7.3 (forced) [Approved]
microsoft-ui-xaml-2-7 package files install completed. Performing other installation steps.
ERROR: The type initializer for '<Module>' threw an exception.
The install of microsoft-ui-xaml-2-7 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-ui-xaml-2-7\tools\chocolateyInstall.ps1'.
 See log for details.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading microsoft-vclibs-140-00 14.0.33321... 100%

microsoft-vclibs-140-00 v14.0.33321 (forced)
microsoft-vclibs-140-00 package files install completed. Performing other installation steps.
ERROR: The type initializer for '<Module>' threw an exception.
The install of microsoft-vclibs-140-00 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
Failed to install winget-cli because a previous dependency failed.
Failed to install winget because a previous dependency failed.

Chocolatey installed 0/4 packages. 4 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - microsoft-ui-xaml-2-7 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-ui-xaml-2-7\tools\chocolateyInstall.ps1'.
 See log for details.
 - microsoft-vclibs-140-00 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
 - winget - Failed to install winget because a previous dependency failed.
 - winget-cli - Failed to install winget-cli because a previous dependency failed.
==> Finished Winget Repair
Checking if Chocolatey is Installed...
===========================================
---      Chocolatey is installed        ---
===========================================
Version: v2.5.0
Chocolatey v2.5.0
Installing the following packages:
winget
By installing, you accept licenses for the packages.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading microsoft-ui-xaml-2-7 2.7.3... 100%

microsoft-ui-xaml-2-7 v2.7.3 (forced) [Approved]
microsoft-ui-xaml-2-7 package files install completed. Performing other installation steps.
ERROR: The type initializer for '<Module>' threw an exception.
The install of microsoft-ui-xaml-2-7 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-ui-xaml-2-7\tools\chocolateyInstall.ps1'.
 See log for details.
Downloading package from source 'https://community.chocolatey.org/api/v2/'
Progress: Downloading microsoft-vclibs-140-00 14.0.33321... 100%

microsoft-vclibs-140-00 v14.0.33321 (forced)
microsoft-vclibs-140-00 package files install completed. Performing other installation steps.
ERROR: The type initializer for '<Module>' threw an exception.
The install of microsoft-vclibs-140-00 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
Failed to install winget-cli because a previous dependency failed.
Failed to install winget because a previous dependency failed.

Chocolatey installed 0/4 packages. 4 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - microsoft-ui-xaml-2-7 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-ui-xaml-2-7\tools\chocolateyInstall.ps1'.
 See log for details.
 - microsoft-vclibs-140-00 (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\chocolateyInstall.ps1'.
 See log for details.
 - winget - Failed to install winget because a previous dependency failed.
 - winget-cli - Failed to install winget-cli because a previous dependency failed.
==> Finished Winget Repair

</pre>

**Comment by chrisjlocke** [comment]
As an aside, ThioJoe has winget install scripts for the sandbox.
https://github.com/ThioJoe/Windows-Sandbox-Tools
