### ISSUE TITLE
System responsiveness

### ISSUE THREAD

**Issue by fifeku** [ChrisTitusTech/winutil#669]
I noticed that after applying all the tweaks on the left side menu, for example opening task manager or file explorer etc. and then closing it, closes it longer and kind of lags the application. Usually closing task manager takes a second, and with the tweaks applied it takes around 4 seconds. I believe that setting the services to manual makes the closing time longer but im not 100% sure. Will there be an option to keep the system fast and at the same time removing all unnecessary crap from running in the background, like a menu where you can select what services to affect.

**Comment by dennyamarojr** [comment]
Hi @fifeku could you provide more information about the Operating system you're using and the version so we can investigate and provide more information with details.
Here's the info we need
Operating System: 
Version and Build of OS: 
Type of Storage is being used for OS, HDD or SSD (we need this info due the recent problem of Windows 11 March Update 2023) Source: https://www.windowscentral.com/software-apps/windows-11/windows-11-march-2023-patch-tuesday-update-may-cut-your-ssd-speed-in-half

About the services there's no setting affecting the speed of computer but telling to the system to only use the service when you open a program or doing some tasks like download windows updates. About the services selection, the project already carefully selects the services and set to manual, so we don't need to worry about any trouble in the system and before any publish/commit @ChrisTitusTech test everything and also other members that contribute to the project test as well.

**Comment by fifeku** [comment]
OS: tested both on Windows 11 Pro 22H2 Moment 2 update and Windows 10 Pro 64-bit.
Version is the newest one available, i can check later with winver.
Storage: Samsung Evo Plus 970 1TB Nvme SSD
I am aware of the SSD speed 50% cut problem, but i did a couple of tests, i installed both Windows 10 and Windows 11 in a virtual machine without using the toolbox, everything ran fast and smooth, apps are closing really fast, after the toolbox and applying all the changes on the left side menu (only this was done, no other tweaking or anything else) after restarting the system the apps took way longer to close and lagged when closing, i will post this interaction to youtube, because i can't really explain it i think.

**Comment by dennyamarojr** [comment]
I get what did you are trying to say, but we need a little bit information about "after applying all the tweaks on the left side menu" could you share the selection of tweaks, so I can investigate and others too

**Comment by fifeku** [comment]
I just confirmed my theory, after only checking the box Set services to manual, the same thing happened i don't exactly know what's causing the issue but i would like to reduce the service number since 120 at boot is a lot, but i don't want to sacrifice my operating system's speed for that.

**Comment by dennyamarojr** [comment]
Hi @fifeku check the services here, and could you apply the services manual tweak again and them before restarting the OS, go to services.msc and them go to SysMain change from Manual to Automatic and Windows Search from manual to automatic (delayed start) and see if this is the cause of the issue

**Comment by fifeku** [comment]
I just tried that and the issue still remains, it has to be some sort of service that i don't know manages window launching or something, genuinelly i have no idea.

**Comment by dennyamarojr** [comment]
In the video you provide you apply the minimal and not just set services to manual, did you try just setting to manual the services? If yes, I will exclude some services and attach a script and you take a look and test to see if the performance is affected

**Comment by dennyamarojr** [comment]
So, I review the list and comment out some services, test and see if the issue is fixed or still present
[set_services-to-manual.zip](https://github.com/ChrisTitusTech/winutil/files/11105390/set_services-to-manual.zip)

The services that I comment out is due the fact is disabled by default, is in manual state by default or is automatic by default, so we don't to configure the services in manual already or even enable the services is disabled by default, the services that is in automatic I change 5 services and should fix the problem, you can see more details below

- **Services that is already in manual state**
  - #"CaptureService_48486de"                                    # Optional screen capture functionality for applications that call the Windows.Graphics.Capture API.
  - #"PerfHost"                                                              # Remote users and 64-bit processes to query performance.
  - #"RetailDemo"                                                          # Demo Mode for Store Display
  - #"seclogon"                                                              # Secondary Logon (Disables other credentials only password will work)
  - #"XblAuthManager"                                                 # Xbox Live Auth Manager (Disabling Breaks Xbox Live Games)
  - #"XblGameSave"                                                      # Xbox Live Game Save Service (Disabling Breaks Xbox Live Games)
  - #"XboxNetApiSvc"                                                   # Xbox Live Networking Service (Disabling Breaks Xbox Live Games)
  - #"XboxGipSvc"                                                         # Xbox Accessory Management Service
  - #"SharedAccess"                                                      # Internet Connection Sharing (ICS)
  - #Hyper-V services
  - #"HvHost"
  - #"vmicguestinterface"
  - #"vmicheartbeat"
  - #"vmickvpexchange"
  - #"vmicrdv"
  - #"vmicshutdown"
  - #"vmictimesync"
  - #"vmicvmsession"

- **Services that is in automatic state**
  - #"cbdhsvc_48486de"                                               # Clipboard Service
  - #"SysMain"                                                               # Analyses System Usage and Improves Performance
  - #"WpnService"                                                         # WpnService (Push Notifications may not work)
  - #"WSearch"                                                              # Windows Search
  - #"FontCache"                                                           # Windows Font cache

- **Services that is in disabled state by default**
  - #"NetTcpPortSharing"                                             # Net.Tcp Port Sharing Service
  - #"RemoteAccess"                                                     # Routing and Remote Access
  - #"RemoteRegistry"                                                   # Remote Registry

**Comment by fifeku** [comment]
I just ran that script and the issue still remains.  Only when closing the task manager.

**Comment by fifeku** [comment]
Oh nevermind, the script didn't execute properly. It works. Thanks you so much for help! Im going to close the issue.
