### ISSUE TITLE
Error Attempting to Uninstall Microsoft Edge

### ISSUE THREAD

**Issue by runninghamster0** [ChrisTitusTech/winutil#727]
Hi,
When trying to uninstall Microsoft Edge by checking the box in the Tweaks section and clicking the 'Run tweaks' button, the relevant script to uninstall Microsoft Edge doesn't seem to be executed.

**To Reproduce**
1. Go to Tweaks
2. Check box for Remove Microsoft Edge
3. Click on Run Tweaks button
4. See error in Terminal

**Expected behavior**
The script to uninstall Edge should be executed.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/52240313/09d68148-6ecf-4cae-9520-6c76bff39cae)
![image](https://github.com/ChrisTitusTech/winutil/assets/52240313/608d049b-8b23-404d-9b79-b54bd3c70158)
![image](https://github.com/ChrisTitusTech/winutil/assets/52240313/ea3ed48d-851d-46fb-bfbe-ff756eba16ad)

**Comment by padsalatushal** [comment]
same problem.  
@DeveloperDurp
 I looked into code as far as i understand "InvokeScript" works fine for "WPFEssTweaksDiskCleanup", "WPFMiscTweaksRightClickMenu" but the problem occur in :
- WPFEssTweaksRemoveCortana
- WPFEssTweaksRemoveEdge
 
I changed the value of InvokeScript in  WPFEssTweaksRemoveEdge for testing and it's work fine. i don't understand Invoke-WinUtilTweaks.ps1 and Invoke-WinUtilFeatureInstall.ps1 files but i think there is problem maybe.

**Comment by padsalatushal** [comment]
@DeveloperDurp 
I think i figure out the issue.
the edge removal script is giving some errors like registry is not found and some others.
and when some error happens script stops it's execution 

```
    Try{
        Invoke-Command $scriptblock -ErrorAction stop
        Write-Host "Running Script for $name"
    }
    Catch{
        Write-Warning "Unable to run script for $name due to unhandled exception"
        Write-Warning $psitem.Exception.StackTrace 
    }
}
```

![image](https://github.com/ChrisTitusTech/winutil/assets/57517785/b1f86f44-2a7c-43fe-8c26-1509b16e4ffa)
I removed try and catch and run this function again it's work fine even the edge removal script gives some error but at the end script ran fine. 


so to solve this issue is there any other way rather than removing try and catch from "Invoke-WinUtilScript" function .

**Comment by DeveloperDurp** [comment]
I realized the issue with WPFEssTweaksRemoveEdge, it's calling a batch file, we would need to change how it's ran in the config so that it pulls the file and runs it with cmd.exe instead of | iex. Though I think @ChrisTitusTech  was thinking of removing this option to begin with.

For WPFEssTweaksRemoveCortana we can add another catch block for the specific error and handle it specifically instead of a generic catch. Similar to how I do it [here](https://github.com/ChrisTitusTech/winutil/blob/main/functions/private/Get-WinUtilRegistry.ps1). You should be able to get the exception by modifying the function and output the error into a variable. It would look something like this and $test will contain all the details about the error.

```powershell
Try{
    Invoke-Command $scriptblock -ErrorAction stop
    Write-Host "Running Script for $name"
}
Catch{
    $test = $psitem
}
```

**Comment by padsalatushal** [comment]
```
    Try {
        Invoke-Command $scriptblock -ErrorAction Stop
        Write-Host "Running Script for $name"
    }
    Catch [System.Management.Automation.CommandNotFoundException] {
        Write-Warning "The specified command was not found."
        Write-Warning $PSItem.Exception.StackTrace
    }
    Catch [System.Management.Automation.RuntimeException] {
        Write-Warning "A runtime exception occurred."
        Write-Warning $PSItem.Exception.StackTrace
    }
    Catch [System.Security.SecurityException] {
        Write-Warning "A security exception occurred."
        Write-Warning $PSItem.Exception.StackTrace
    }
    Catch [System.UnauthorizedAccessException] {
        Write-Warning "Access denied. You do not have permission to perform this operation."
        Write-Warning $PSItem.Exception.StackTrace
    }
    Catch {
        # Generic catch block to handle any other type of exception
        Write-Warning "An unhandled exception occurred."
        Write-Warning $PSItem.Exception.StackTrace
    }
    
```
@DeveloperDurp take a look

**Comment by DeveloperDurp** [comment]
So far so good, I would avoid putting the stack trace inside exceptions that we are handling, it can cause confusion for the user if they get a huge wall of text. Though depending on the message I believe $psitem.exception.message can include useful information.

**Comment by padsalatushal** [comment]
@DeveloperDurp 
![image](https://github.com/ChrisTitusTech/winutil/assets/57517785/80cb1beb-8518-44d9-99e0-196738926d23)

is UndoScript not working or i am doing something wrong. can you please explain how can I use UndoScript?

**Comment by padsalatushal** [comment]
Resolved in #750

**Comment by DeveloperDurp** [comment]
@padsalatushal Currently there is no undo script functions, could be implemented fairly easily as I skipped it to prioritize the registry, services and scheduled tasks. 

you would only need to add the undoscript to the config file and modify this function 
https://github.com/ChrisTitusTech/winutil/blob/main/functions/private/Invoke-WinUtilTweaks.ps1

**Comment by padsalatushal** [comment]
@DeveloperDurp I get the config file part but can you explain more on https://github.com/ChrisTitusTech/winutil/blob/main/functions/private/Invoke-WinUtilTweaks.ps1 
in this file what to modify and where to modify?
sorry for this type of dump question.

**Comment by DeveloperDurp** [comment]
These lines execute the script blocks from the config file. Currently it will only run if the undo variable is false. You would need to move this out of that block.

https://github.com/ChrisTitusTech/winutil/blob/2c6b4598707b8f29c2bddf74bf92e52d5cf72380/functions/private/Invoke-WinUtilTweaks.ps1#L50-L54

From there you would need to modify the following lines so you can provide the correct scriptblock to the function based if the undo variable is true or false.

https://github.com/ChrisTitusTech/winutil/blob/2c6b4598707b8f29c2bddf74bf92e52d5cf72380/functions/private/Invoke-WinUtilTweaks.ps1#L13-L26

**Comment by DeveloperDurp** [comment]
going to tag @ChrisTitusTech  as there is some decent information here that might help him as well.

**Comment by padsalatushal** [comment]
@runninghamster0 
It is resolved in #750 you can close this issue.

**Comment by brandleesee** [comment]
Currently unable to uninstall or remove Microsoft Edge because "Winget failed to install" despite installing in from the Microsoft Store. Is there a solution for installing Winget? (I'd rather not open a new issue unless absolutely necessary - tried installing winget through this link but to no avail: https://apps.microsoft.com/store/detail/app-installer/9NBLGGH4NNS1?hl=en-mt&gl=mt&rtc=1)

Thank you in advance.

![image](https://github.com/ChrisTitusTech/winutil/assets/12674437/6ed0adf5-c8d1-47d0-89d8-4fd95720e3a8)

**Comment by padsalatushal** [comment]
> Currently unable to uninstall or remove Microsoft Edge because "Winget failed to install" despite installing in from the Microsoft Store. Is there a solution for installing Winget? (I'd rather not open a new issue unless absolutely necessary - tried installing winget through this link but to no avail: https://apps.microsoft.com/store/detail/app-installer/9NBLGGH4NNS1?hl=en-mt&gl=mt&rtc=1)
> 
> Thank you in advance.
> 
> ![image](https://user-images.githubusercontent.com/12674437/241550348-6ed0adf5-c8d1-47d0-89d8-4fd95720e3a8.png)

for installing winget :
open PowerShell as admin and run following commands:
```
Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
Install-Script -Name winget-install -Force
winget-install.ps1
```

**Comment by brandleesee** [comment]
Thank you, @padsalatushal, had some hiccups but winget was installed successfully.

Re: the removal of Microsoft Edge, something seems amiss.

The install failed with the exit code 93.

Just in case, restarted the laptop and Edge functioned normally, i.e. not installed.

Any pointers on this, please? Thank you in advance.

![image](https://github.com/ChrisTitusTech/winutil/assets/12674437/f5b39575-fab1-40be-a717-9ec1ad9122ea)

**Comment by padsalatushal** [comment]
@brandleesee For removing edge go to the tweaks section and select "Remove Microsoft Edge" and click on Run Tweak Button

**Comment by brandleesee** [comment]
@padsalatushal, thank you for your help. 

Initially, that is the procedure I adopted but because it was not successful, I opted to install chocolatey/winget and uninstall it from there since there are two options to remove Microsoft Edge (Winget uninstall selection Edge OR Tweaks Remove Microsoft Edge).

The below screen shows that Edge and Webview were removed, however, after restarting the computer, Edge was still visible in Start Menu and fully functional.

Anything else I can try, please?

![image](https://github.com/ChrisTitusTech/winutil/assets/12674437/61e2ddab-b9aa-4db6-8621-8fed42b21c3f)

**Comment by padsalatushal** [comment]
@brandleesee edge is usually come back after updating windows. can you try one more time and also tell me which windows version are you using? I tested remove edge features on multiple systems and it's work.

**Comment by brandleesee** [comment]
Yes, sure!

## From Tweaks Tab

Unsuccessful.

![image](https://github.com/ChrisTitusTech/winutil/assets/12674437/9739d97e-b712-4d65-ad48-028dc70babfe)

![image](https://github.com/ChrisTitusTech/winutil/assets/12674437/3604fd28-d5e7-43b2-80d1-b25c4ba60c61)

## From Winget

Unsuccessful.

![image](https://github.com/ChrisTitusTech/winutil/assets/12674437/5c0863e5-2fa9-42c2-9d47-519407a5c206)

![image](https://github.com/ChrisTitusTech/winutil/assets/12674437/d8656c32-0c19-4848-bb01-542ab0475a98)

![image](https://github.com/ChrisTitusTech/winutil/assets/12674437/e292bf59-ad66-4a01-85a4-b83e6a082a9f)

**Comment by brandleesee** [comment]
Further to the above post, after restart, Microsoft Edge is still visible and fully functional.

Hardware specs follow:

https://kelaptop.com/en/acer-spin-1-sp111-31-c4av-nx-gl2ek-004

Basics:
Acer Spin 1 SP111-31-C4AV
Windows 10 Home

**Comment by padsalatushal** [comment]
@brandleesee 
I will work on this issue .
For now, if you want to remove edge checkout: https://github.com/padsalatushal/Edge-Removal

**Comment by brandleesee** [comment]
Thank you, @padsalatushal!
Your batch script worked well, with some caveats. The entry in Microsoft Edge has remained. However, when I click on it, the browser does not start - which is good. Another thing I noticed is that the Edge install is still present on Windows. In any case, Edge no longer works now!

**Comment by Davy49** [comment]
Hi All,
I'm really hoping that in the near future that it will be a lot easier to uninstall microsoft edge while using the one tool for everything utility software, of course I really feel like one of the major issues with trying to uninstall ms edge is how it's so intertwined within the operating system.

**Comment by ChrisTitusTech** [comment]
Thanks @padsalatushal I'm going to use your bat script
Fixed in commit https://github.com/ChrisTitusTech/winutil/commit/b2e3def5116c391d84b47f6c38f108290ae833bd
