### ISSUE TITLE
nuke windows defender

### ISSUE THREAD

**Issue by hitesh920** [ChrisTitusTech/winutil#778]
**Is your feature request related to a problem? Please describe.**
i hate antivurs 

**Describe the solution you'd like**
please add a option to disable windows defender completely

**Comment by tristengrant** [comment]
Why would you want to disable it?

**Comment by TakenMC** [comment]
That is a bad idea

**Comment by d0x360** [comment]
Gotta agree not a good idea.  Defenders from my experience is the least intrusive or resource wasting av software I've ever used as far as I can remember.

I usually tell it to ignore my game folders and disable CFG for intense games or games with tons of drm (aka all ubi games) and I haven't had an infection in years and I do scan with a 3rd party av suite once a month then I uninstall it.

Adguard+defender plus a good router is my daily method for online activities and it's kept me safe for years...along with not downloading insane random files lol

**Comment by TheOverpassArsonist** [comment]
firmly disagree with the decision here. Disabling Defender isn't for day to day normal-use but I'm currently trying, and struggling, to make an extremely stripped down W11 VM and the Antimalware Service Executable process alone is taking around 10% of the RAM of the entire system along with being responsible for or contributing to most significant idle-CPU spikes I can see and consistently taking disk IO, along with being responsible for many major overall resource spikes at idle. In fact, on a cold boot it (stably) uses over 4x more memory than the second highest memory using process on the entire system. (32.4mb to 133.3mb) This script already has changes that are explicitly labeled as being potentially dangerous and not-advisable for normal users, so drawing the line at Windows Defender is an extremely strange choice. 

I can't think of any situation where a normal user would actively want to disable IPv6, yet that's an option. Meanwhile creating extremely lean VM's where you are either actively testing malware to see how it behaves and _want_ to allow infections or (more likely) simply don't care if it gets infected because it's an isolated and trivially reproducible VM don't seem like wild usecases to me. Admittedly there is obvious bias in that they're _my_ current usecase, but I equally wouldn't suggest removing the option to disable IPv6 just because I don't personally see the use for it. There are already options clearly marked as potentially breaking the system and this is a utility specifically designed to allow technical users to quickly reproduce system configurations that would otherwise be annoying or a waste of time to reproduce manually, bypassing a low level component like Windows' builtin AV fits that exactly.

Things like completely disabling the microsoft store, completely disabling updates, etc. break a system (and/or make it more vulnerable) as-much if not more than disabling defender, yet those are included features because the user should get to decide what fits their usecase. Dangerous and/or ill-advised tweaks are already included and clearly labeled and this is already a toolkit thats rather niche and hard to find unless you know what you're looking for in the first place. Anyone using this tool should know what they're doing and, even if they don't, they're given clear warnings of what buttons they shouldn't be pressing. If people want to break their system with this toolkit they already can and frankly there is no way to stop that, but there is very real utility and value in disabling Windows Defender in the right use cases - use cases that, as far as I'd reason, are likely far more common than use cases that would be required for some of these other breaking changes to be justified. An offline system doesn't need to disable windows updates because it can't connect to MS servers to download any updates, meaning there is a button already in this script to intentionally disable all security updates for an online system. That is a far less justifiable use case than simply being able to turn off Windows Defender, which will continue to eat resources (a non-negligible amount of resources, again, 4x more than 2nd place) whether you're online and being exposed to threats or offline and running exclusively trusted programs in an air-gapped VM. Let me stress that my point it not that there are **_no_** valid use cases for turning off updates, there are, and a stripped down VM is one of them, (it only has network access for if a niche utility or something needs it to work properly) but my point is that the number of 'valid usecases' for turning off updates are far fewer than the number of 'valid usecases' for turning off the builtin AV because the builtin AV will continue to be a relevant resource hog even completely offline and in a secure, isolated environment whereas turning off updates won't be relevant if the device has no internet connection. 

Update : The AMSE process is currently using 50% of my VM's CPU, 500MB of memory, and 10MB/s disk IO at the time of me finishing this reply. These are significant resource spikes that confer absolutely zero advantages in the context of a highly isolated, easily restorable VM.
