### ISSUE TITLE
Tweeks are not working since last update

### ISSUE THREAD

**Issue by esyx-xyse** [ChrisTitusTech/winutil#804]
I had debloated my win 11 a few months ago with this tool down to about 60-70 processes but when I now run exactly the same on another PC with a new win 11 installation almost nothing changes... not even the Edge browser will be removed.. After running the "Tweeks", even the widget and search function at the bottom of the taskbar reappear and some other things are set back to default.

![Screenshot_68](https://github.com/ChrisTitusTech/winutil/assets/69367138/25145812-33de-43da-85c8-5a4b4ad35ad3)

I packed the Powershell logs into a pastebin. (German)
https://pastebin.com/JkQXGZ22

**Comment by padsalatushal** [comment]
Are you running Powershell as admin?

**Comment by esyx-xyse** [comment]
> Are you running Powershell as admin?

Yes, of course.

**Comment by esyx-xyse** [comment]
@padsalatushal Yes, of course.

**Comment by esyx-xyse** [comment]
> Are you running Powershell as admin?

@padsalatushal Yes, of course.

**Comment by FPSBRONSON** [comment]
Since the last update, I can no longer use the free version of the software on my PC. I keep receiving a list of errors highlighted in yellow, running the default PC Tweaks. I have the default recommended settings for Windows Update, but it keeps updating and causing issues. I suspect that the large update might be the root of the problem. The main issue is that certain games won't open. I've tried restoring my PC several times, but during two of the attempts, I couldn't select any options in the tweaks section of the tool. I use this tool almost every day to clean my PC, and I really enjoy it. I'm just waiting for the issues to be fixed, so I can start using it again. I'm not very technical, so I don't know if anything has been fixed by reading this forum. I've been checking Chris's homepage for updates, hoping for some news.

**Comment by esyx-xyse** [comment]
> Since the last update, I can no longer use the free version of the software on my PC. I keep receiving a list of errors highlighted in yellow, running the default PC Tweaks. I have the default recommended settings for Windows Update, but it keeps updating and causing issues. I suspect that the large update might be the root of the problem. The main issue is that certain games won't open. I've tried restoring my PC several times, but during two of the attempts, I couldn't select any options in the tweaks section of the tool. I use this tool almost every day to clean my PC, and I really enjoy it. I'm just waiting for the issues to be fixed, so I can start using it again. I'm not very technical, so I don't know if anything has been fixed by reading this forum. I've been checking Chris's homepage for updates, hoping for some news.

@FPSBRONSON Yes, no, so far there has been no new update, so I think it will still take a while for something to come. So far it's been 3 weeks...

**Comment by Nulimitz** [comment]
@FPSBRONSON I stopped using it because of all the errors switching the startup of services. Hopefully they can get this working again soon.

**Comment by ChrisTitusTech** [comment]
Thanks for the report, I've commited 10101a4 that does a conditional statement to see if the service exists before setting it.
Also, if a service is set to manual it will attempt to stop the service during the runtime.

**Comment by Nulimitz** [comment]
Just tested this and it works without a hitch. Thank you Chris.
