### ISSUE TITLE
Edge not uninstalling

### ISSUE THREAD

**Issue by insanity83NL** [ChrisTitusTech/winutil#884]
**Describe the bug**
Upon using this tool I've ticked Edge, and pressed the uninstall button in the top

**To Reproduce**

1. Open the tool 
2. Tick Edge and click the uninstall button on the top
3. Script is executing
4. Error:

Found Microsoft Edge [Microsoft.Edge]
Starting package uninstall...
Uninstall failed with exit code: 93

**Expected behavior**
Edge to be uninstalled

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/115035124/ed534d13-ddc5-48ae-a3c9-4dbcbdbf81e0)

![image](https://github.com/ChrisTitusTech/winutil/assets/115035124/8245a9ca-a1f3-4868-9392-fb48f256e93e)

**Additional context**
.

**Comment by ChrisTitusTech** [comment]
Fixed in commit b2e3def

**Comment by einsteinx2** [comment]
This is failing for me now on latest Windows 11 pro update, same error, using latest version of your tool

**Comment by einsteinx2** [comment]
Ahh actually it's only broken in the Install tab. If I choose Edge and click the uninstall button I get the error 93, but when I selected Remove Microsoft Edge in the Tweaks tab, it popped open a new shell window with a blue background, ran some other script and successfully uninstalled it.

So I assume the fix in that commit only changed the Tweaks tab.

**Comment by PeteSapai** [comment]
Can confirm that uninstalling from the Install tab still yields error 93.

Runnning it from the Tweaks tab gives an OK, but Edge is still there and is able to run. Running it a 2nd time gives:
"WARNING: A runtime exception occurred.
WARNING: This command cannot be run due to the error: The system cannot find the file specified."

The reason I tried this tool is because the other uninstall method (running "setup.exe --uninstall --system-level --verbose-logging --force-uninstall") doesn't seem to work anymore. Might those 2 be related?

**Comment by HAK3R4LIFE** [comment]
bruh still no fix..
