### ISSUE TITLE
Winget Install issue still present on Win10 LTSC

### ISSUE THREAD

**Issue by CaptainV0408** [ChrisTitusTech/winutil#956]
**Describe the bug**
The issue from #943 and #943 is still present on Windows 10 IoT Enterprise LTSC 21H2 190444.3324 .

**To Reproduce**
1. Install any program through winget on an LTSC machine.

**Expected behavior**
Winget should be installed and should work.

**Screenshots**
![Winget failed Install](https://github.com/ChrisTitusTech/winutil/assets/141863162/ecfed772-4fe1-45dc-8d4c-832761d9c373)

**Additional context**
Probably a compatibilty issue with LTSC version of Windows 10

**Comment by ChrisTitusTech** [comment]
I'm fairly sure it is missing a store dependency in LTSC that would require more packages. 

Since LTSC users probably don't want to install anything Microsoft Store related, I think the best option is to failover to Chocolatey which is being worked on.

**Comment by Rust1667** [comment]
This is the easiest method I found to install Winget on LTSC:
1. Install [WingetUI](https://github.com/marticliment/WingetUI)
2. With WingetUI, search for the package [App Installer](https://apps.microsoft.com/store/detail/app-installer/9NBLGGH4NNS1) in the source "Winget: msstore", and install it with Administrator Privileges.
Thats all.

Alternative method: instead of WingetUI, [App Installer](https://apps.microsoft.com/store/detail/app-installer/9NBLGGH4NNS1) could also be installed with [alt-app-installer](https://github.com/m-jishnu/alt-app-installer)

**Comment by KALIXHOSTING** [comment]
On LTSC Versions Just make sure you have all the updates installed first then use `choco install winget` via powershell install it then rerun winutil tool and all should be well and working as shown in screenshots below 
![winget](https://github.com/ChrisTitusTech/winutil/assets/93708739/6ac4d648-1590-4f4f-8471-58a87a43a6cd)
![wingetinstall successful](https://github.com/ChrisTitusTech/winutil/assets/93708739/c5e66e9c-5e4e-4356-b914-0324f312929e)
![working](https://github.com/ChrisTitusTech/winutil/assets/93708739/f4b7d332-9882-441c-878d-e54ec13d8737)
